export const briefFixes = {
  "files/p-08": "Input a whole number N. Input N lines of text, one at a time. Write them to `lines.txt`, one per line. Reopen the file and print the line that has the most characters (spaces count as characters). If two lines have the same length, print the one that came first.",
  "combining-techniques/p-05": "A bus starts empty. Input a whole number N, the number of stops. At each stop, input how many people get on, then how many people get off (there are always enough people on the bus to get off).\n\nPrint two lines: how many people are on the bus after the final stop, then the highest number of people that were on the bus at any point, counted after each stop.",
};

export const testFixes = {
  "files/p-s1": [{ from: "2\nred blue red\nred green", to: "2\nred blue red\nred green\nred" }],
};

export const topics = {
  files: {
    "p-01": { solution: `name = input()\nscore = input()\nf = open("highscore.txt", "w")\nf.write(name + ": " + score + "\\n")\nf.close()\nf = open("highscore.txt", "r")\nprint(f.read())\nf.close()`, extra: ["Sam\n7", "Mia Rose\n100", "Bo\n0"] },
    "p-02": { solution: `message = input()\nf = open("log.txt", "a")\nf.write(message + "\\n")\nf.close()\nf = open("log.txt", "r")\nprint(f.read())\nf.close()`, extra: ["Disk full", "Ann logged in", "x"] },
    "p-03": { solution: `n = int(input())\nf = open("notes.txt", "w")\nfor i in range(n):\n    f.write(input() + "\\n")\nf.close()\nf = open("notes.txt", "r")\nprint(len(f.readlines()))\nf.close()`, extra: ["1\nonly", "4\na\nb\nc\nd", "2\nx y\nz"] },
    "p-04": { solution: `n = int(input())\nf = open("readings.txt", "w")\nfor i in range(n):\n    f.write(input() + "\\n")\nf.close()\nf = open("readings.txt", "r")\ntotal = 0\ncount = 0\nfor line in f:\n    total = total + int(line)\n    count = count + 1\nf.close()\nprint(round(total / count, 2))`, extra: ["1\n10", "4\n1\n2\n3\n4", "2\n7\n8"] },
    "p-05": { solution: `n = int(input())\nf = open("guests.txt", "w")\nfor i in range(n):\n    f.write(input() + "\\n")\nf.close()\nwanted = input()\nf = open("guests.txt", "r")\nfound = False\nfor line in f:\n    if line.strip() == wanted:\n        found = True\nf.close()\nif found:\n    print("Found")\nelse:\n    print("Not found")`, extra: ["1\nAda\nAda", "2\nAda\nAlan\nada", "3\nA\nB\nC\nC"] },
    "p-06": { solution: `first = input()\nf = open("data.txt", "w")\nf.write(first + "\\n")\nf.close()\nsecond = input()\nf = open("data.txt", "w")\nf.write(second + "\\n")\nf.close()\nf = open("data.txt", "r")\nprint(f.read())\nf.close()`, extra: ["a\nb", "one\none", "x y\nz"] },
    "p-07": { solution: `n = int(input())\nf = open("essay.txt", "w")\nfor i in range(n):\n    f.write(input() + "\\n")\nf.close()\nf = open("essay.txt", "r")\ntotal = 0\nfor line in f:\n    total = total + len(line.split())\nf.close()\nprint(total)`, extra: ["1\none", "3\na b\nc d e\nf", "2\nhello world\nfoo bar baz"] },
    "p-08": { solution: `n = int(input())\nf = open("lines.txt", "w")\nfor i in range(n):\n    f.write(input() + "\\n")\nf.close()\nf = open("lines.txt", "r")\nlongest = ""\nfirst = True\nfor line in f:\n    line = line.rstrip("\\n")\n    if first or len(line) > len(longest):\n        longest = line\n        first = False\nf.close()\nprint(longest)`, extra: ["1\nx", "3\nabc\ndef\nab", "2\na bit\nlonger line here"] },
    "p-09": { solution: `n = int(input())\nf = open("numbers.txt", "w")\nfor i in range(n):\n    f.write(input() + "\\n")\nf.close()\nf = open("numbers.txt", "r")\nkept = []\nfor line in f:\n    if int(line) > 10:\n        kept.append(line.strip())\nf.close()\nout = open("filtered.txt", "w")\nout.write(" ".join(kept))\nout.close()\nf = open("filtered.txt", "r")\ntext = f.read()\nf.close()\nif text == "":\n    print("None")\nelse:\n    print(text)`, extra: ["1\n11", "4\n10\n11\n12\n9", "2\n5\n10"] },
    "p-10": { solution: `n1 = int(input())\nf = open("file_a.txt", "w")\nfor i in range(n1):\n    f.write(input() + "\\n")\nf.close()\nn2 = int(input())\nf = open("file_b.txt", "w")\nfor i in range(n2):\n    f.write(input() + "\\n")\nf.close()\nmerged = open("merged.txt", "w")\nfor name in ["file_a.txt", "file_b.txt"]:\n    part = open(name, "r")\n    merged.write(part.read())\n    part.close()\nmerged.close()\nf = open("merged.txt", "r")\nprint(f.read())\nf.close()`, extra: ["1\na\n1\nb", "3\nx\ny\nz\n1\nw", "1\nsolo\n2\np\nq"] },
    "p-s1": { solution: `n = int(input())\nf = open("source.txt", "w")\nfor i in range(n):\n    f.write(input() + "\\n")\nf.close()\nword = input()\nf = open("source.txt", "r")\ncount = 0\nfor line in f:\n    for w in line.split():\n        if w == word:\n            count = count + 1\nf.close()\nout = open("result.txt", "w")\nout.write(word + ": " + str(count) + "\\n")\nout.close()\nf = open("result.txt", "r")\nprint(f.read())\nf.close()`, extra: ["1\nno match here\nyes", "2\na a a\nb\na", "1\nThe the THE\nthe"] },
    "p-s2": { solution: `n = int(input())\nf = open("report.csv", "w")\nfor i in range(n):\n    name = input()\n    score = input()\n    f.write(name + "," + score + "\\n")\nf.close()\nf = open("report.csv", "r")\ntotal = 0\ncount = 0\nfor line in f:\n    total = total + int(line.strip().split(",")[1])\n    count = count + 1\nf.close()\nf = open("report.csv", "a")\nf.write("Average," + str(round(total / count, 2)) + "\\n")\nf.close()\nf = open("report.csv", "r")\nprint(f.read())\nf.close()`, extra: ["1\nAda\n50", "2\nAda\n80\nSam\n85", "3\nA\n10\nB\n20\nC\n25"] },
  },
  "combining-techniques": {
    "p-01": { solution: `n = int(input())\ncount = 0\nfor i in range(n):\n    if int(input()) > 0:\n        count = count + 1\nprint(count)`, extra: ["1\n5", "3\n-1\n-2\n0", "4\n0\n1\n2\n3"] },
    "p-02": { solution: `n = int(input())\nfor i in range(n):\n    size = int(input())\n    if size >= 3 and size <= 12:\n        print("Available")\n    else:\n        print("Out of stock")`, extra: ["1\n3", "2\n12\n13", "4\n2\n3\n12\n13"] },
    "p-03": { solution: `n = int(input())\nbest = None\nfor i in range(n):\n    x = int(input())\n    if x % 2 == 0 and (best is None or x > best):\n        best = x\nif best is None:\n    print("None")\nelse:\n    print(best)`, extra: ["1\n4", "3\n-4\n-2\n-6", "4\n2\n2\n2\n2", "1\n7"] },
    "p-04": { solution: `n = int(input())\ncount = 0\ntotal = 0\nfor i in range(n):\n    x = int(input())\n    if x % 2 != 0:\n        count = count + 1\n        total = total + x\nprint(count)\nprint(total)`, extra: ["1\n3", "3\n2\n4\n6", "4\n1\n1\n1\n1"] },
    "p-05": { solution: `n = int(input())\non_bus = 0\nhighest = 0\nfor i in range(n):\n    on_bus = on_bus + int(input())\n    on_bus = on_bus - int(input())\n    if on_bus > highest:\n        highest = on_bus\nprint(on_bus)\nprint(highest)`, extra: ["1\n5\n0", "2\n3\n1\n0\n2", "4\n1\n0\n1\n0\n1\n0\n1\n0"] },
  },
};
