export const briefFixes = {
  "sequencing/p-03": "A phone plan charges 3p per text message. Input the number of texts sent. Print the total cost in pounds, rounded to 2 decimal places.\n\nFor example, 100 texts cost 3 pounds.",
  "sequencing/p-s2": "Input a ticket price (which may include pence), then the number of friends going (a whole number), then a snacks budget (which may include pence).\n\nThe total cost is the ticket price times the number of friends, plus the snacks budget. Each friend pays an equal share, rounded to 2 decimal places. Because of the rounding, the shares may not add up to exactly the total. The leftover is the total minus (each friend's rounded share × the number of friends).\n\nPrint three lines, with every amount rounded to 2 decimal places: `Total: £<amount>`, `Each pays: £<amount>` and `Leftover: £<amount>`.",
};

export const topics = {
  sequencing: {
    "p-01": { solution: `a = int(input())\nb = int(input())\nc = int(input())\nprint(a + b + c)`, extra: ["0\n0\n0", "100\n200\n300", "-5\n-5\n-5"] },
    "p-02": { solution: `gross = int(input())\ntax = int(input())\nprint(gross - tax)`, extra: ["1000\n250", "20\n20", "750\n0"] },
    "p-03": { solution: `texts = int(input())\nprint(round(texts * 3 / 100, 2))`, extra: ["0", "250", "1", "33"] },
    "p-04": { solution: `total = 0\nfor i in range(4):\n    total = total + float(input())\nprint(round(total / 4, 1))`, extra: ["10\n10\n10\n10", "6\n7\n8\n9", "9.5\n8.5\n9\n9"] },
    "p-05": { solution: `distance = float(input())\nprint(round(distance / 12 * 1.45, 2))`, extra: ["12", "240", "7", "0"] },
    "p-06": { solution: `total = float(input())\npeople = int(input())\nprint(round(total / people, 2))`, extra: ["60\n4", "20.50\n2", "10\n3", "9\n1"] },
    "p-07": { solution: `cakes = int(input())\npacks = int(input())\nprint("Raised: £" + str(round(cakes * 2.5 + packs * 0.8, 2)))`, extra: ["0\n0", "2\n1", "8\n11", "1\n0"] },
    "p-08": { solution: `distance = int(input())\nspeed = int(input())\nminutes = round(distance / speed * 60)\nprint(str(minutes // 60) + "h " + str(minutes % 60) + "m")`, extra: ["60\n60", "100\n40", "45\n30", "10\n60"] },
    "p-09": { solution: `price = float(input())\npct = int(input())\ndiscount = round(price * pct / 100, 2)\nfinal = round(price - discount, 2)\nprint("Discount: £" + str(discount))\nprint("Final: £" + str(final))`, extra: ["19.99\n15", "100\n0", "60\n50"] },
    "p-10": { solution: `cars = int(input())\naverage = float(input())\nown = float(input())\nwait = cars * average\ntotal = wait + own\nprint("Wait: " + str(wait) + "s")\nprint("Total: " + str(total) + "s")\nprint("Minutes: " + str(round(total / 60, 1)))`, extra: ["0\n45\n30", "10\n30\n90", "2\n37.5\n60"] },
    "p-s1": { solution: `cost = int(input())\npaid = int(input())\nchange = paid - cost\nprint("Pounds: " + str(change // 100))\nprint("Pence: " + str(change % 100))`, extra: ["99\n100", "250\n1000", "1999\n2000"] },
    "p-s2": { solution: `price = float(input())\nfriends = int(input())\nsnacks = float(input())\ntotal = price * friends + snacks\neach = round(total / friends, 2)\nleftover = round(total - each * friends, 2)\nprint("Total: £" + str(round(total, 2)))\nprint("Each pays: £" + str(each))\nprint("Leftover: £" + str(leftover))`, extra: ["12\n5\n0", "9.99\n3\n5", "4\n1\n1"] },
  },
  selection: {
    "p-01": { solution: `age = int(input())\nif age >= 18:\n    print("Can vote")\nelse:\n    print("Cannot vote")`, extra: ["18", "17", "100", "0"] },
    "p-02": { solution: `n = int(input())\nif n > 0:\n    print("Positive")\nelif n < 0:\n    print("Negative")\nelse:\n    print("Zero")`, extra: ["1", "-1", "100", "-50"] },
    "p-03": { solution: `speed = int(input())\nif speed > 30:\n    print("Speeding")\nelse:\n    print("Within limit")`, extra: ["30", "31", "0", "70"] },
    "p-04": { solution: `age = int(input())\nif age >= 18:\n    print("18")\nelif age >= 15:\n    print("15")\nelif age >= 12:\n    print("12")\nelse:\n    print("U")`, extra: ["18", "15", "12", "14", "11", "17", "0"] },
    "p-05": { solution: `used = int(input())\nif used > 500:\n    print("Over allowance: " + str(used - 500) + "MB")\nelse:\n    print("Remaining: " + str(500 - used) + "MB")`, extra: ["500", "501", "0", "499"] },
    "p-06": { solution: `score = int(input())\nif score >= 40:\n    print("Pass")\nelse:\n    print("Fail")`, extra: ["40", "39", "100", "0"] },
    "p-07": { solution: `n = int(input())\nif n == 0:\n    print("Zero")\nelif n % 2 == 0:\n    print("Even")\nelse:\n    print("Odd")`, extra: ["-3", "-4", "1", "100"] },
    "p-08": { solution: `a = int(input())\nb = int(input())\nc = int(input())\nsides = sorted([a, b, c])\nif sides[0] + sides[1] <= sides[2]:\n    print("Not a triangle")\nelif a == b and b == c:\n    print("Equilateral")\nelif a == b or b == c or a == c:\n    print("Isosceles")\nelse:\n    print("Scalene")`, extra: ["2\n2\n3", "5\n5\n10", "6\n8\n10", "10\n1\n10", "2\n3\n5"] },
    "p-09": { solution: `spend = float(input())\ncard = input()\nif card == "yes":\n    if spend >= 100:\n        pct = 20\n    elif spend >= 50:\n        pct = 10\n    else:\n        pct = 5\nelse:\n    if spend >= 100:\n        pct = 10\n    elif spend >= 50:\n        pct = 5\n    else:\n        pct = 0\nfinal = round(spend * (100 - pct) / 100, 2)\nprint("Discount: " + str(pct) + "%")\nprint("Final: £" + str(final))`, extra: ["50\nyes", "49.99\nno", "100\nno", "75\nno", "99.99\nyes"] },
    "p-10": { solution: `score = int(input())\nresit = input()\nif score >= 80:\n    grade = "A*"\nelif score >= 70:\n    grade = "A"\nelif score >= 60:\n    grade = "B"\nelif score >= 50:\n    grade = "C"\nelif score >= 40:\n    grade = "D"\nelse:\n    grade = "U"\nprint(grade)\nif resit == "yes" and (grade == "D" or grade == "U"):\n    print("Resit recommended")`, extra: ["80\nno", "79\nno", "40\nyes", "39\nno", "60\nyes", "50\nno", "70\nyes"] },
    "p-s1": { solution: `age = int(input())\nexperience = int(input())\nclaims = int(input())\npremium = 500\nif age < 25:\n    premium = premium + 300\nif experience < 2:\n    premium = premium + 150\npremium = premium + 100 * claims\nprint("Premium: £" + str(premium))\nif claims >= 3:\n    print("High risk — refer to underwriter")`, extra: ["24\n2\n0", "25\n1\n3", "18\n0\n2", "25\n2\n2"] },
    "p-s2": { solution: `income = float(input())\ntax = 0\nif income > 50000:\n    tax = tax + (income - 50000) * 0.4\n    income = 50000\nif income > 12000:\n    tax = tax + (income - 12000) * 0.2\nprint("Tax owed: £" + str(round(tax, 2)))`, extra: ["12000", "12001.50", "50000", "100000", "0"] },
  },
  iteration: {
    "p-01": { solution: `n = int(input())\nfor i in range(n, 0, -1):\n    print(i)`, extra: ["1", "6", "10"] },
    "p-02": { solution: `n = int(input())\ntotal = 0\nfor i in range(2, n + 1, 2):\n    total = total + i\nprint(total)`, extra: ["1", "2", "20", "9"] },
    "p-03": { solution: `name = input()\ncount = int(input())\nfor i in range(count):\n    print("Hello, " + name + "!")`, extra: ["Sam\n1", "Bo\n4", "Mia Rose\n2"] },
    "p-04": { solution: `n = int(input())\nwhile n > 0:\n    print(n)\n    n = n - 1\nprint("Liftoff!")`, extra: ["1", "5", "0"] },
    "p-05": { solution: `n = int(input())\nlimit = int(input())\nvalue = n\nwhile value <= limit:\n    print(value)\n    value = value + n`, extra: ["5\n20", "7\n7", "4\n10", "10\n35"] },
    "p-06": { solution: `n = int(input())\ntotal = 0\nfor i in range(1, n + 1):\n    total = total + i\nprint(total)`, extra: ["1", "100", "3"] },
    "p-07": { solution: `n = int(input())\nlargest = int(input())\nfor i in range(n - 1):\n    value = int(input())\n    if value > largest:\n        largest = value\nprint(largest)`, extra: ["1\n-5", "3\n-2\n-9\n-4", "5\n1\n9\n9\n3\n2"] },
    "p-08": { solution: `n = int(input())\nwhile n >= 0:\n    print(n)\n    n = n - 2`, extra: ["2", "0", "20", "8"] },
    "p-09": { solution: `n = int(input())\nlimit = int(input())\nfor i in range(1, limit + 1):\n    print(str(i) + " x " + str(n) + " = " + str(i * n))`, extra: ["5\n1", "12\n3", "7\n2"] },
    "p-10": { solution: `start = int(input())\nend = int(input())\nfor n in range(start, end + 1):\n    if n % 15 == 0:\n        print("FizzBuzz")\n    elif n % 3 == 0:\n        print("Fizz")\n    elif n % 5 == 0:\n        print("Buzz")\n    else:\n        print(n)`, extra: ["15\n15", "3\n3", "5\n6", "28\n31"] },
    "p-s1": { solution: `n = int(input())\nprime = True\nfor i in range(2, n):\n    if n % i == 0:\n        prime = False\nif prime:\n    print("Prime")\nelse:\n    print("Not prime")`, extra: ["9", "13", "4", "97", "91"] },
    "p-s2": { solution: `n = int(input())\nfor row in range(n, 0, -1):\n    print("*" * row)`, extra: ["1", "5", "2"] },
  },
};
