export const briefFixes = {
  "lists/p-04": "Input a whole number N, then N more whole numbers, storing them in a list. Print the second-highest value in the list.\n\nIf the highest value appears more than once, ignore the repeats: the second-highest is the largest value that is smaller than the highest. Every list in the tests has at least two different values.\n\nFor example, 10, 30, 20, 5 prints `20`, and 9, 9, 7 prints `7`.",
  "lists/p-s2": "Input a whole number N, then N more whole numbers, building a list. Input a rotation amount K (a whole number from 0 up to N).\n\nPrint the list rotated left by K positions: the first K items move to the end, in order. Print the numbers on one line separated by spaces.\n\nFor example, 1, 2, 3, 4, 5 rotated left by 2 prints `3 4 5 1 2`.",
  "strings/p-03": "Input a word, then a single letter. Print how many times that letter appears in the word.\n\nOnly the exact letter counts, so a capital `A` is a different letter from a lower case `a`.\n\nFor example, `banana` and `a` prints `3`.",
  "strings/p-05": "Input a word. Print `Palindrome` if it reads the same forwards and backwards, otherwise print `Not a palindrome`.\n\nCapital letters count as different letters, so `Level` is not a palindrome but `level` is.",
  "strings/p-08": "Input a sentence. Print how many words it contains. The words are separated by single spaces.\n\nFor example, `the quick brown fox` prints `4`.",
};

export const topics = {
  lists: {
    "p-01": { solution: `n = int(input())\nwords = []\nfor i in range(n):\n    words.append(input())\nfor i in range(n - 1, -1, -1):\n    print(words[i])`, extra: ["1\nsolo", "4\na\nb\nc\nd", "2\nx\nx"] },
    "p-02": { solution: `n = int(input())\ntotal = 0\nfor i in range(n):\n    name = input()\n    total = total + int(input())\nprint(total)`, extra: ["1\nEggs\n12", "3\nA\n1\nB\n2\nC\n3", "2\nTea\n0\nJam\n4"] },
    "p-03": { solution: `n = int(input())\nnumbers = []\nfor i in range(n):\n    numbers.append(int(input()))\ntarget = int(input())\ncount = 0\nfor x in numbers:\n    if x == target:\n        count = count + 1\nprint(count)`, extra: ["3\n1\n1\n1\n1", "4\n5\n6\n7\n8\n9", "1\n4\n4"] },
    "p-04": { solution: `n = int(input())\nnumbers = []\nfor i in range(n):\n    numbers.append(int(input()))\nhighest = max(numbers)\nsecond = None\nfor x in numbers:\n    if x != highest and (second is None or x > second):\n        second = x\nprint(second)`, extra: ["3\n1\n2\n3", "5\n9\n9\n7\n7\n3", "2\n8\n4", "4\n-1\n-5\n-3\n-9"] },
    "p-05": { solution: `n = int(input())\nnumbers = []\nfor i in range(n):\n    numbers.append(int(input()))\nprint(len(set(numbers)))`, extra: ["1\n4", "4\n1\n2\n3\n4", "6\n2\n2\n2\n2\n2\n2"] },
    "p-06": { solution: `n = int(input())\ntotal = 0\nfor i in range(n):\n    total = total + int(input())\nprint(total)`, extra: ["1\n9", "5\n-1\n1\n-1\n1\n5", "3\n10\n20\n30"] },
    "p-07": { solution: `n = int(input())\nitems = []\nfor i in range(n):\n    items.append(input())\nprint(items[0])\nprint(items[-1])`, extra: ["1\nonly", "4\na\nb\nc\nd", "2\nx y\nz"] },
    "p-08": { solution: `n = int(input())\nevens = []\nfor i in range(n):\n    x = int(input())\n    if x % 2 == 0:\n        evens.append(str(x))\nif len(evens) == 0:\n    print("None")\nelse:\n    print(" ".join(evens))`, extra: ["1\n2", "4\n2\n4\n6\n8", "3\n-2\n-3\n0", "1\n7"] },
    "p-09": { solution: `n = int(input())\nseen = []\nfor i in range(n):\n    x = int(input())\n    if x not in seen:\n        seen.append(x)\nprint(" ".join(str(x) for x in seen))`, extra: ["1\n9", "5\n3\n2\n3\n2\n1", "3\n1\n2\n3"] },
    "p-10": { solution: `n = int(input())\nnames = []\nscores = []\nfor i in range(n):\n    names.append(input())\n    scores.append(input())\nwanted = input()\nif wanted in names:\n    print(wanted + ": " + scores[names.index(wanted)])\nelse:\n    print("Not found")`, extra: ["1\nAda\n80\nAda", "3\nAda\n80\nSam\n65\nMia\n90\nMia", "2\nAda\n80\nSam\n65\nada"] },
    "p-s1": { solution: `a = int(input())\nnumbers = []\nfor i in range(a):\n    numbers.append(int(input()))\nb = int(input())\nfor i in range(b):\n    numbers.append(int(input()))\nnumbers.sort()\nprint(" ".join(str(x) for x in numbers))`, extra: ["1\n5\n1\n3", "2\n4\n4\n2\n4\n4", "3\n9\n8\n7\n1\n1"] },
    "p-s2": { solution: `n = int(input())\nnumbers = []\nfor i in range(n):\n    numbers.append(int(input()))\nk = int(input())\nrotated = numbers[k:] + numbers[:k]\nprint(" ".join(str(x) for x in rotated))`, extra: ["3\n1\n2\n3\n0", "3\n1\n2\n3\n3", "3\n7\n8\n9\n1", "1\n5\n1"] },
  },
  strings: {
    "p-01": { solution: `word = input()\nprint(word[0])\nprint(word[-1])`, extra: ["a", "Hi", "level"] },
    "p-02": { solution: `sentence = input()\nprint(sentence.upper())`, extra: ["already LOUD", "mixed Case 123", "z"] },
    "p-03": { solution: `word = input()\nletter = input()\ncount = 0\nfor c in word:\n    if c == letter:\n        count = count + 1\nprint(count)`, extra: ["banana\nb", "hello\nz", "Mississippi\ns", "AaAa\na"] },
    "p-04": { solution: `word = input()\nreversed_word = ""\nfor c in word:\n    reversed_word = c + reversed_word\nprint(reversed_word)`, extra: ["a", "level", "Python"] },
    "p-05": { solution: `word = input()\nif word == word[::-1]:\n    print("Palindrome")\nelse:\n    print("Not a palindrome")`, extra: ["a", "noon", "abca", "Level"] },
    "p-06": { solution: `sentence = input()\nprint(sentence.replace(" ", ""))`, extra: ["  leading", "no_spaces", "a  b"] },
    "p-07": { solution: `word = input()\nprint(word[0].upper() + word[1:].lower())`, extra: ["a", "mIXeD", "Python"] },
    "p-08": { solution: `sentence = input()\nprint(len(sentence.split(" ")))`, extra: ["a b c d e", "word", "one two"] },
    "p-09": { solution: `word = input()\ncount = 0\nfor c in word.lower():\n    if c in "aeiou":\n        count = count + 1\nprint(count)`, extra: ["AEIOU", "sky", "Education"] },
    "p-10": { solution: `word = input()\nshifted = ""\nfor c in word:\n    shifted = shifted + chr((ord(c) - ord("a") + 1) % 26 + ord("a"))\nprint(shifted)`, extra: ["z", "hello", "zebra"] },
    "p-s1": { solution: `word = input()\nresult = ""\ni = 0\nwhile i < len(word):\n    count = 1\n    while i + count < len(word) and word[i + count] == word[i]:\n        count = count + 1\n    result = result + word[i] + str(count)\n    i = i + count\nprint(result)`, extra: ["a", "aabbbb", "abab", "zzzzzzzzzzzz"] },
    "p-s2": { solution: `sentence = input()\ncleaned = sentence.replace(" ", "").lower()\nif cleaned == cleaned[::-1]:\n    print("Palindrome")\nelse:\n    print("Not a palindrome")`, extra: ["A man a plan a canal Panama", "Not one", "aa", "x"] },
  },
  functions: {
    "p-01": { solution: `def greet(name):\n    return "Hello, " + name + "!"\n\nprint(greet(input()))`, extra: ["Sam", "Mia Rose"] },
    "p-02": { solution: `def double(n):\n    return n * 2\n\nprint(double(int(input())))`, extra: ["0", "-4", "21"] },
    "p-03": { solution: `def is_even(n):\n    return n % 2 == 0\n\nif is_even(int(input())):\n    print("Even")\nelse:\n    print("Odd")`, extra: ["0", "-2", "1", "100"] },
    "p-04": { solution: `def max_of_two(a, b):\n    if a > b:\n        return a\n    return b\n\nx = int(input())\ny = int(input())\nprint(max_of_two(x, y))`, extra: ["3\n8", "5\n5", "-2\n-9", "0\n0"] },
    "p-05": { solution: `def add_vat(price):\n    return round(price * 1.2, 2)\n\nprint(add_vat(float(input())))`, extra: ["0", "100", "9.99", "1"] },
    "p-06": { solution: `def square(n):\n    return n * n\n\nprint("Square: " + str(square(int(input()))))`, extra: ["0", "-3", "12"] },
    "p-07": { solution: `def min_of_three(a, b, c):\n    smallest = a\n    if b < smallest:\n        smallest = b\n    if c < smallest:\n        smallest = c\n    return smallest\n\nx = int(input())\ny = int(input())\nz = int(input())\nprint(min_of_three(x, y, z))`, extra: ["1\n1\n1", "-5\n0\n5", "9\n3\n3"] },
    "p-08": { solution: `def celsius_to_fahrenheit(c):\n    return round(c * 9 / 5 + 32, 2)\n\nprint("Fahrenheit: " + str(celsius_to_fahrenheit(float(input()))))`, extra: ["-40", "25", "36.6"] },
    "p-09": { solution: `def rectangle_area(w, h):\n    return w * h\n\ndef rectangle_perimeter(w, h):\n    return 2 * (w + h)\n\nw = float(input())\nh = float(input())\nprint("Area: " + str(rectangle_area(w, h)))\nprint("Perimeter: " + str(rectangle_perimeter(w, h)))`, extra: ["2\n7", "1.5\n2", "10\n10"] },
    "p-10": { solution: `def classify(score):\n    if score >= 40:\n        return "Pass"\n    return "Fail"\n\ndef bonus(score):\n    if score >= 90:\n        return 5\n    return 0\n\nscore = int(input())\nprint(classify(score))\nprint("Bonus: " + str(bonus(score)))`, extra: ["40", "90", "89", "39", "100"] },
    "p-s1": { solution: `def factorial(n):\n    result = 1\n    for i in range(2, n + 1):\n        result = result * i\n    return result\n\ndef is_valid(n):\n    return n >= 0\n\nn = int(input())\nif is_valid(n):\n    print(factorial(n))\nelse:\n    print("Invalid input")`, extra: ["1", "3", "10", "-1"] },
    "p-s2": { solution: `def c_to_f(c):\n    return round(c * 9 / 5 + 32, 2)\n\ndef f_to_c(f):\n    return round((f - 32) * 5 / 9, 2)\n\ndef c_to_k(c):\n    return round(c + 273.15, 2)\n\nvalue = float(input())\ncode = input()\nif code == "CF":\n    print("Result: " + str(c_to_f(value)))\nelif code == "FC":\n    print("Result: " + str(f_to_c(value)))\nelse:\n    print("Result: " + str(c_to_k(value)))`, extra: ["37\nCF", "212\nFC", "-273.15\nCK", "0\nCK", "-40\nCF"] },
  },
};
