// More practice for "Strings": length, slicing, upper/lower, searching, looping through characters.
export const tasks = [
  {
    key: "11", tier: 1, difficulty: 1, xp: 10, title: "How long is the word?",
    brief: "Input a word. Print `It has ` followed by the number of characters in the word, then ` letters`.\n\nFor example, `apple` prints `It has 5 letters`. Always write the word `letters` like this, even when the word has just 1.",
    hints: ["`len()` gives the number of characters in a piece of text.", "`print(\"It has \" + str(len(word)) + \" letters\")`"],
    inputs: ["apple", "a", "encyclopedia", "hi there"],
    solution: `word = input()\nprint("It has " + str(len(word)) + " letters")`,
  },
  {
    key: "12", tier: 1, difficulty: 1, xp: 10, title: "Capital letters",
    brief: "Input some text. Print it in capital letters (upper case).\n\nFor example, `hello there` prints `HELLO THERE`.",
    hints: ["Text has built-in methods. One of them turns every letter into a capital.", "`text.upper()` gives the capital-letter version of `text`."],
    inputs: ["hello there", "Python", "abc123", "ALREADY LOUD"],
    solution: `text = input()\nprint(text.upper())`,
  },
  {
    key: "13", tier: 2, difficulty: 2, xp: 15, title: "First three letters",
    brief: "Input a word that has at least 3 letters. Print just its first three letters.\n\nFor example, `computer` prints `com`.",
    hints: ["You can take part of a piece of text with a slice, written with square brackets and a colon.", "`word[0:3]` gives the characters at positions 0, 1 and 2 (the end position is not included)."],
    inputs: ["computer", "cat", "python", "abcdef"],
    solution: `word = input()\nprint(word[0:3])`,
  },
  {
    key: "14", tier: 2, difficulty: 2, xp: 15, title: "Which letter?",
    brief: "Input a word, then a whole number N. Print the letter at position N in the word, counting from 0 for the first letter.\n\nFor example, `python` and `2` prints `t`. You can assume N is a valid position in the word.",
    hints: ["The first letter of a word is at position 0, not 1.", "Square brackets pick one character: `word[n]` (remember to convert the input N with `int()`)."],
    inputs: ["python\n2", "python\n0", "hello\n4", "a\n0", "computer\n5"],
    solution: `word = input()\nn = int(input())\nprint(word[n])`,
  },
  {
    key: "15", tier: 2, difficulty: 2, xp: 15, title: "Starts with a vowel?",
    brief: "Input a word in lower case. Print `Vowel` if it starts with a, e, i, o or u. Otherwise print `Consonant`.\n\nFor example, `orange` prints `Vowel` and `banana` prints `Consonant`.",
    hints: ["Look at just the first letter, `word[0]`.", "Test it with `in`: `if word[0] in \"aeiou\":`."],
    inputs: ["orange", "banana", "egg", "sky", "umbrella", "a"],
    solution: `word = input()\nif word[0] in "aeiou":\n    print("Vowel")\nelse:\n    print("Consonant")`,
  },
  {
    key: "16", tier: 3, difficulty: 3, xp: 20, title: "Count the words with a letter",
    brief: "Input a whole number N (at least 1). Then input N words, one per line, followed by a single letter. Print how many of the N words contain that letter (anywhere in the word).\n\nFor example, the words `apple`, `banana`, `cherry` and the letter `a` prints `2`. The comparison is exact, so `A` and `a` are different.",
    hints: ["Read the N words first, then the letter (or read the words into a list as you go).", "`if letter in word:` tells you whether a word contains the letter. Keep a counter."],
    inputs: ["3\napple\nbanana\ncherry\na", "3\napple\nbanana\ncherry\nz", "2\nsee\nbee\ne", "1\nSam\ns", "4\ndog\ncat\nbat\nfish\nt"],
    solution: `n = int(input())\nwords = []\nfor i in range(n):\n    words.append(input())\nletter = input()\ncount = 0\nfor word in words:\n    if letter in word:\n        count = count + 1\nprint(count)`,
  },
  {
    key: "17", tier: 3, difficulty: 3, xp: 20, title: "Initials",
    brief: "Input a first name, then a last name. Print their initials in capital letters, each followed by a full stop, like `A.L.`\n\nFor example, `ada` and `lovelace` prints `A.L.`",
    hints: ["The initial is the first character of each name, `name[0]`, made into a capital with `.upper()`.", "Join: first initial, `\".\"`, last initial, `\".\"`."],
    inputs: ["ada\nlovelace", "Sam\nlee", "mia\nKHAN", "z\ny"],
    solution: `first = input()\nlast = input()\nprint(first[0].upper() + "." + last[0].upper() + ".")`,
  },
  {
    key: "18", tier: 3, difficulty: 3, xp: 20, title: "Password strength",
    brief: "Input a password. Print `Strong` if it has all three of these:\n- at least 8 characters\n- at least one digit (0 to 9)\n- at least one capital letter (A to Z)\n\nOtherwise print `Weak`.",
    hints: ["Check the length first with `len()`. Then use a loop through the characters to look for a digit and a capital.", "`for ch in password:` then `if ch in \"0123456789\":` sets a variable such as `has_digit = True`. Capitals: `if ch in \"ABCDEFGHIJKLMNOPQRSTUVWXYZ\":`."],
    inputs: ["Password1", "password1", "PASSWORD1", "Password", "Pass1", "Abcdefg1", "12345678"],
    solution: `password = input()\nhas_digit = False\nhas_capital = False\nfor ch in password:\n    if ch in "0123456789":\n        has_digit = True\n    if ch in "ABCDEFGHIJKLMNOPQRSTUVWXYZ":\n        has_capital = True\nif len(password) >= 8 and has_digit and has_capital:\n    print("Strong")\nelse:\n    print("Weak")`,
  },
  {
    key: "19", tier: 4, difficulty: 4, xp: 30, title: "Swap the case",
    brief: "Input some text. Print it with every capital letter changed to lower case and every lower case letter changed to a capital. Characters that are not letters (spaces, digits, punctuation) stay the same.\n\nFor example, `Hello World 1!` prints `hELLO wORLD 1!`.",
    hints: ["Go through the text one character at a time and build up a new piece of text.", "For each character, `ch.isupper()` is True for capitals and `ch.islower()` for lower case. Use `.lower()` or `.upper()` to change it, otherwise keep it as it is."],
    inputs: ["Hello World 1!", "abc", "ABC", "Python 3", "mIxEd CaSe"],
    solution: `text = input()\nresult = ""\nfor ch in text:\n    if ch.isupper():\n        result = result + ch.lower()\n    elif ch.islower():\n        result = result + ch.upper()\n    else:\n        result = result + ch\nprint(result)`,
  },
  {
    key: "20", tier: 4, difficulty: 4, xp: 30, title: "Longest word",
    brief: "Input a sentence made of words separated by single spaces. Print the longest word. If two or more words are tied for longest, print the first of them.\n\nFor example, `the quick brown fox` prints `quick`.",
    hints: ["`sentence.split()` breaks the text into a list of words.", "Keep a variable `longest = \"\"`. For each word, if `len(word) > len(longest)`, replace it. Using `>` (not `>=`) keeps the first of any tie."],
    inputs: ["the quick brown fox", "hello", "a bb cc d", "one two six", "python is great fun"],
    solution: `sentence = input()\nlongest = ""\nfor word in sentence.split():\n    if len(word) > len(longest):\n        longest = word\nprint(longest)`,
  },
  {
    key: "s3", tier: 4, difficulty: 5, xp: 40, stretch: true, title: "🌟 Anagram check",
    brief: "Two words are anagrams if they use exactly the same letters the same number of times, just in a different order (for example `listen` and `silent`).\n\nInput two words in lower case, one per line. Print `Anagrams` if they are anagrams, otherwise print `Not anagrams`. A word is not counted as an anagram of itself in this task - if both words are exactly the same, print `Not anagrams`.",
    hints: ["Two words with the same letters will look identical if you sort their letters into alphabetical order.", "`sorted(word)` gives a list of a word's letters in order. Compare `sorted(a) == sorted(b)`, and also check that `a != b`."],
    inputs: ["listen\nsilent", "cat\nact", "cat\ncar", "hello\nhello", "abc\nabcd", "dusty\nstudy"],
    solution: `a = input()\nb = input()\nif a != b and sorted(a) == sorted(b):\n    print("Anagrams")\nelse:\n    print("Not anagrams")`,
  },
  {
    key: "s4", tier: 4, difficulty: 5, xp: 40, stretch: true, title: "🌟 Compress the spaces",
    brief: "Input some text that may contain extra spaces (several spaces in a row, or spaces at the start or end). Print the text with every group of spaces replaced by a single space, and no spaces at the very start or end.\n\nFor example, `  a   b  c ` prints `a b c`.",
    hints: ["`text.split()` with nothing inside the brackets splits on any amount of spaces and ignores the ones at the ends.", "Join the pieces back together with single spaces: `\" \".join(words)`."],
    inputs: ["  a   b  c ", "hello world", "one", "   lots    of   space   ", "a  b"],
    solution: `text = input()\nwords = text.split()\nprint(" ".join(words))`,
  },
];
