/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDuelsRouteImport } from './routes/_authenticated/duels'
import { Route as AuthenticatedIdeRouteImport } from './routes/_authenticated/ide'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedPracticeRouteImport } from './routes/_authenticated/practice'
import { Route as AuthenticatedRecapRouteImport } from './routes/_authenticated/recap'
import { Route as AuthenticatedHomeworkHomeworkIdRouteImport } from './routes/_authenticated/homework.$homeworkId'
import { Route as AuthenticatedLearnIndexRouteImport } from './routes/_authenticated/learn.index'
import { Route as AuthenticatedLearnLessonSlugRouteImport } from './routes/_authenticated/learn.$lessonSlug'
import { Route as AuthenticatedPlaySlugRouteImport } from './routes/_authenticated/play.$slug'
import { Route as AuthenticatedTeacherIndexRouteImport } from './routes/_authenticated/teacher.index'
import { Route as AuthenticatedTeacherClassIdRouteImport } from './routes/_authenticated/teacher.$classId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDuelsRoute = AuthenticatedDuelsRouteImport.update({
  id: '/duels',
  path: '/duels',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIdeRoute = AuthenticatedIdeRouteImport.update({
  id: '/ide',
  path: '/ide',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPracticeRoute = AuthenticatedPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecapRoute = AuthenticatedRecapRouteImport.update({
  id: '/recap',
  path: '/recap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeworkHomeworkIdRoute =
  AuthenticatedHomeworkHomeworkIdRouteImport.update({
    id: '/homework/$homeworkId',
    path: '/homework/$homeworkId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLearnIndexRoute = AuthenticatedLearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLearnLessonSlugRoute =
  AuthenticatedLearnLessonSlugRouteImport.update({
    id: '/learn/$lessonSlug',
    path: '/learn/$lessonSlug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlaySlugRoute = AuthenticatedPlaySlugRouteImport.update({
  id: '/play/$slug',
  path: '/play/$slug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeacherIndexRoute =
  AuthenticatedTeacherIndexRouteImport.update({
    id: '/teacher/',
    path: '/teacher/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeacherClassIdRoute =
  AuthenticatedTeacherClassIdRouteImport.update({
    id: '/teacher/$classId',
    path: '/teacher/$classId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/duels': typeof AuthenticatedDuelsRoute
  '/ide': typeof AuthenticatedIdeRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/practice': typeof AuthenticatedPracticeRoute
  '/recap': typeof AuthenticatedRecapRoute
  '/homework/$homeworkId': typeof AuthenticatedHomeworkHomeworkIdRoute
  '/learn/$lessonSlug': typeof AuthenticatedLearnLessonSlugRoute
  '/play/$slug': typeof AuthenticatedPlaySlugRoute
  '/teacher/$classId': typeof AuthenticatedTeacherClassIdRoute
  '/learn/': typeof AuthenticatedLearnIndexRoute
  '/teacher/': typeof AuthenticatedTeacherIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/duels': typeof AuthenticatedDuelsRoute
  '/ide': typeof AuthenticatedIdeRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/practice': typeof AuthenticatedPracticeRoute
  '/recap': typeof AuthenticatedRecapRoute
  '/homework/$homeworkId': typeof AuthenticatedHomeworkHomeworkIdRoute
  '/learn/$lessonSlug': typeof AuthenticatedLearnLessonSlugRoute
  '/play/$slug': typeof AuthenticatedPlaySlugRoute
  '/teacher/$classId': typeof AuthenticatedTeacherClassIdRoute
  '/learn': typeof AuthenticatedLearnIndexRoute
  '/teacher': typeof AuthenticatedTeacherIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/duels': typeof AuthenticatedDuelsRoute
  '/_authenticated/ide': typeof AuthenticatedIdeRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/practice': typeof AuthenticatedPracticeRoute
  '/_authenticated/recap': typeof AuthenticatedRecapRoute
  '/_authenticated/homework/$homeworkId': typeof AuthenticatedHomeworkHomeworkIdRoute
  '/_authenticated/learn/$lessonSlug': typeof AuthenticatedLearnLessonSlugRoute
  '/_authenticated/play/$slug': typeof AuthenticatedPlaySlugRoute
  '/_authenticated/teacher/$classId': typeof AuthenticatedTeacherClassIdRoute
  '/_authenticated/learn/': typeof AuthenticatedLearnIndexRoute
  '/_authenticated/teacher/': typeof AuthenticatedTeacherIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/duels'
    | '/ide'
    | '/leaderboard'
    | '/practice'
    | '/recap'
    | '/homework/$homeworkId'
    | '/learn/$lessonSlug'
    | '/play/$slug'
    | '/teacher/$classId'
    | '/learn/'
    | '/teacher/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/duels'
    | '/ide'
    | '/leaderboard'
    | '/practice'
    | '/recap'
    | '/homework/$homeworkId'
    | '/learn/$lessonSlug'
    | '/play/$slug'
    | '/teacher/$classId'
    | '/learn'
    | '/teacher'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/duels'
    | '/_authenticated/ide'
    | '/_authenticated/leaderboard'
    | '/_authenticated/practice'
    | '/_authenticated/recap'
    | '/_authenticated/homework/$homeworkId'
    | '/_authenticated/learn/$lessonSlug'
    | '/_authenticated/play/$slug'
    | '/_authenticated/teacher/$classId'
    | '/_authenticated/learn/'
    | '/_authenticated/teacher/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/duels': {
      id: '/_authenticated/duels'
      path: '/duels'
      fullPath: '/duels'
      preLoaderRoute: typeof AuthenticatedDuelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ide': {
      id: '/_authenticated/ide'
      path: '/ide'
      fullPath: '/ide'
      preLoaderRoute: typeof AuthenticatedIdeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/practice': {
      id: '/_authenticated/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof AuthenticatedPracticeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recap': {
      id: '/_authenticated/recap'
      path: '/recap'
      fullPath: '/recap'
      preLoaderRoute: typeof AuthenticatedRecapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/homework/$homeworkId': {
      id: '/_authenticated/homework/$homeworkId'
      path: '/homework/$homeworkId'
      fullPath: '/homework/$homeworkId'
      preLoaderRoute: typeof AuthenticatedHomeworkHomeworkIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn/': {
      id: '/_authenticated/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof AuthenticatedLearnIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn/$lessonSlug': {
      id: '/_authenticated/learn/$lessonSlug'
      path: '/learn/$lessonSlug'
      fullPath: '/learn/$lessonSlug'
      preLoaderRoute: typeof AuthenticatedLearnLessonSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/play/$slug': {
      id: '/_authenticated/play/$slug'
      path: '/play/$slug'
      fullPath: '/play/$slug'
      preLoaderRoute: typeof AuthenticatedPlaySlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher/': {
      id: '/_authenticated/teacher/'
      path: '/teacher'
      fullPath: '/teacher/'
      preLoaderRoute: typeof AuthenticatedTeacherIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher/$classId': {
      id: '/_authenticated/teacher/$classId'
      path: '/teacher/$classId'
      fullPath: '/teacher/$classId'
      preLoaderRoute: typeof AuthenticatedTeacherClassIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDuelsRoute: typeof AuthenticatedDuelsRoute
  AuthenticatedIdeRoute: typeof AuthenticatedIdeRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedPracticeRoute: typeof AuthenticatedPracticeRoute
  AuthenticatedRecapRoute: typeof AuthenticatedRecapRoute
  AuthenticatedHomeworkHomeworkIdRoute: typeof AuthenticatedHomeworkHomeworkIdRoute
  AuthenticatedLearnLessonSlugRoute: typeof AuthenticatedLearnLessonSlugRoute
  AuthenticatedPlaySlugRoute: typeof AuthenticatedPlaySlugRoute
  AuthenticatedTeacherClassIdRoute: typeof AuthenticatedTeacherClassIdRoute
  AuthenticatedLearnIndexRoute: typeof AuthenticatedLearnIndexRoute
  AuthenticatedTeacherIndexRoute: typeof AuthenticatedTeacherIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDuelsRoute: AuthenticatedDuelsRoute,
  AuthenticatedIdeRoute: AuthenticatedIdeRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedPracticeRoute: AuthenticatedPracticeRoute,
  AuthenticatedRecapRoute: AuthenticatedRecapRoute,
  AuthenticatedHomeworkHomeworkIdRoute: AuthenticatedHomeworkHomeworkIdRoute,
  AuthenticatedLearnLessonSlugRoute: AuthenticatedLearnLessonSlugRoute,
  AuthenticatedPlaySlugRoute: AuthenticatedPlaySlugRoute,
  AuthenticatedTeacherClassIdRoute: AuthenticatedTeacherClassIdRoute,
  AuthenticatedLearnIndexRoute: AuthenticatedLearnIndexRoute,
  AuthenticatedTeacherIndexRoute: AuthenticatedTeacherIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
