create unique index if not exists lessons_slug_key on public.lessons (slug);
create unique index if not exists challenges_slug_key on public.challenges (slug);

insert into public.lessons (slug,track,topic,order_index,title,summary) values
('gcse-iteration-1','gcse','iteration',1,'Count-controlled loops','for loops and range().'),
('gcse-iteration-2','gcse','iteration',2,'Condition-controlled loops','while loops, sentinel values and validation.'),
('gcse-iteration-3','gcse','iteration',3,'Exam-style iteration problems','Choosing the right loop and tracking several values at once.'),
('gcse-lists-1','gcse','lists',1,'Making and indexing lists','Storing many values under one name.'),
('gcse-lists-2','gcse','lists',2,'Searching, totalling and 2D lists','Linear search, aggregation and lists of lists.'),
('gcse-lists-3','gcse','lists',3,'Exam-style list problems','Building, filtering and reporting on data sets.'),
('gcse-selection-1','gcse','selection',1,'if, else and comparisons','Making a program choose between two paths.'),
('gcse-selection-2','gcse','selection',2,'elif chains and logical operators','More than two options, and conditions joined with and/or/not.'),
('gcse-selection-3','gcse','selection',3,'Exam-style selection problems','Working out the boundaries from a written scenario.'),
('gcse-sequencing-1','gcse','sequencing',1,'Input, output and variables','Read data in, store it, print it back out.'),
('gcse-sequencing-2','gcse','sequencing',2,'Arithmetic and rounding','Calculations, integer division and formatting numbers.'),
('gcse-sequencing-3','gcse','sequencing',3,'Exam-style sequencing problems','Longer scenarios where you decide the steps yourself.')
on conflict (slug) do update set track=excluded.track,topic=excluded.topic,order_index=excluded.order_index,title=excluded.title,summary=excluded.summary;

insert into public.challenges (slug,track,topic,title,brief,difficulty,xp,wording_tier,lesson_id,lesson_order)
select v.slug,v.track::track,v.topic,v.title,'',v.difficulty,v.xp,v.tier,l.id,v.ord from (values
('gcse-iteration-t1-01','gcse','iteration','Repeat a word',1,10,1,'gcse-iteration-1',1),
('gcse-iteration-t1-02','gcse','iteration','Count down',1,10,1,'gcse-iteration-1',2),
('gcse-iteration-t1-03','gcse','iteration','Even numbers',2,15,1,'gcse-iteration-1',3),
('gcse-iteration-t2-01','gcse','iteration','Five scores',2,15,2,'gcse-iteration-2',4),
('gcse-iteration-t2-02','gcse','iteration','Password retry',3,20,2,'gcse-iteration-2',5),
('gcse-iteration-t2-03','gcse','iteration','Validate a mark',3,20,2,'gcse-iteration-2',6),
('gcse-iteration-t3-01','gcse','iteration','Rainfall readings',3,25,3,'gcse-iteration-3',7),
('gcse-iteration-t3-02','gcse','iteration','Class average until done',4,30,3,'gcse-iteration-3',8),
('gcse-iteration-t3-03','gcse','iteration','Savings target',4,30,3,'gcse-iteration-3',9),
('gcse-iteration-t4-01','gcse','iteration','Turnstile counter',4,35,4,'gcse-iteration-3',10),
('gcse-iteration-t4-02','gcse','iteration','Times table tester',5,40,4,'gcse-iteration-3',11),
('gcse-iteration-t4-03','gcse','iteration','Energy meter report',5,40,4,'gcse-iteration-3',12),
('gcse-lists-t1-01','gcse','lists','First and last',1,10,1,'gcse-lists-1',1),
('gcse-lists-t1-02','gcse','lists','List total',2,15,1,'gcse-lists-1',2),
('gcse-lists-t1-03','gcse','lists','Print in reverse',2,15,1,'gcse-lists-1',3),
('gcse-lists-t2-01','gcse','lists','Highest and lowest',2,15,2,'gcse-lists-2',4),
('gcse-lists-t2-02','gcse','lists','Search a register',3,20,2,'gcse-lists-2',5),
('gcse-lists-t2-03','gcse','lists','Count above average',3,20,2,'gcse-lists-2',6),
('gcse-lists-t3-01','gcse','lists','Sorted scoreboard',3,25,3,'gcse-lists-3',7),
('gcse-lists-t3-02','gcse','lists','Stock check',4,30,3,'gcse-lists-3',8),
('gcse-lists-t3-03','gcse','lists','Seating grid',4,30,3,'gcse-lists-3',9),
('gcse-lists-t4-01','gcse','lists','Sports day results',4,35,4,'gcse-lists-3',10),
('gcse-lists-t4-02','gcse','lists','Club membership search',5,40,4,'gcse-lists-3',11),
('gcse-lists-t4-03','gcse','lists','Tuck shop takings',5,40,4,'gcse-lists-3',12),
('gcse-selection-t1-01','gcse','selection','Positive or negative',1,10,1,'gcse-selection-1',1),
('gcse-selection-t1-02','gcse','selection','Old enough to vote',1,10,1,'gcse-selection-1',2),
('gcse-selection-t1-03','gcse','selection','Bigger of two',2,15,1,'gcse-selection-1',3),
('gcse-selection-t2-01','gcse','selection','Traffic light',2,15,2,'gcse-selection-2',4),
('gcse-selection-t2-02','gcse','selection','In range',3,20,2,'gcse-selection-2',5),
('gcse-selection-t2-03','gcse','selection','Login with two checks',3,20,2,'gcse-selection-2',6),
('gcse-selection-t3-01','gcse','selection','Swimming pool entry',3,25,3,'gcse-selection-3',7),
('gcse-selection-t3-02','gcse','selection','Parcel size checker',4,30,3,'gcse-selection-3',8),
('gcse-selection-t3-03','gcse','selection','Quiz feedback',4,30,3,'gcse-selection-3',9),
('gcse-selection-t4-01','gcse','selection','Theme park ride restrictions',4,35,4,'gcse-selection-3',10),
('gcse-selection-t4-02','gcse','selection','Broadband billing',5,40,4,'gcse-selection-3',11),
('gcse-selection-t4-03','gcse','selection','Library fine system',5,40,4,'gcse-selection-3',12),
('gcse-sequencing-t1-01','gcse','sequencing','Print a message',1,10,1,'gcse-sequencing-1',1),
('gcse-sequencing-t1-02','gcse','sequencing','Double a number',1,10,1,'gcse-sequencing-1',2),
('gcse-sequencing-t1-03','gcse','sequencing','Add two numbers',1,10,1,'gcse-sequencing-1',3),
('gcse-sequencing-t1-04','gcse','sequencing','Full name',2,15,1,'gcse-sequencing-1',4),
('gcse-sequencing-t2-01','gcse','sequencing','Seconds to minutes',2,15,2,'gcse-sequencing-2',5),
('gcse-sequencing-t2-02','gcse','sequencing','Average of three marks',2,15,2,'gcse-sequencing-2',6),
('gcse-sequencing-t2-03','gcse','sequencing','Change from a note',2,15,2,'gcse-sequencing-2',7),
('gcse-sequencing-t2-04','gcse','sequencing','Perimeter and area',3,20,2,'gcse-sequencing-2',8),
('gcse-sequencing-t3-01','gcse','sequencing','Sponsored walk',3,25,3,'gcse-sequencing-3',9),
('gcse-sequencing-t3-02','gcse','sequencing','Cinema booking',3,25,3,'gcse-sequencing-3',10),
('gcse-sequencing-t3-03','gcse','sequencing','Fuel efficiency',3,25,3,'gcse-sequencing-3',11),
('gcse-sequencing-t3-04','gcse','sequencing','Packing boxes',4,30,3,'gcse-sequencing-3',12),
('gcse-sequencing-t4-01','gcse','sequencing','Sports club membership',4,35,4,'gcse-sequencing-3',13),
('gcse-sequencing-t4-02','gcse','sequencing','Temperature conversion utility',4,35,4,'gcse-sequencing-3',14),
('gcse-sequencing-t4-03','gcse','sequencing','Payroll slip',5,40,4,'gcse-sequencing-3',15),
('gcse-sequencing-t4-04','gcse','sequencing','Delivery charge calculator',5,40,4,'gcse-sequencing-3',16)
) as v(slug,track,topic,title,difficulty,xp,tier,lesson_slug,ord) join public.lessons l on l.slug=v.lesson_slug
on conflict (slug) do update set title=excluded.title,difficulty=excluded.difficulty,xp=excluded.xp,wording_tier=excluded.wording_tier,lesson_id=excluded.lesson_id,lesson_order=excluded.lesson_order;