-- GENERATED by scripts/build-assessment-seed.mjs from src/content/assessments/*.json.
-- Do not edit by hand - change the JSON and regenerate. Safe to re-run.
-- 30 questions.

INSERT INTO public.assessment_questions (id, track, board, topic, marks, ability, answer_format, question)
VALUES ($aq$ocr-iteration-01$aq$, 'gcse', $aq$ocr$aq$, $aq$iteration$aq$, 2, 1, $aq$text$aq$, $aq$Identify **two** types of loop (iteration) used in programming. [2]$aq$)
ON CONFLICT (id) DO UPDATE SET board = EXCLUDED.board, topic = EXCLUDED.topic, marks = EXCLUDED.marks,
  ability = EXCLUDED.ability, answer_format = EXCLUDED.answer_format, question = EXCLUDED.question;
DELETE FROM public.assessment_mark_points WHERE question_id = $aq$ocr-iteration-01$aq$ AND position > 2;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$ocr-iteration-01$aq$, 1, $aq$Count-controlled loop (accept: FOR loop)$aq$, 1, $aq$Accept a correct example of the loop written in code.$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$ocr-iteration-01$aq$, 2, $aq$Condition-controlled loop (accept: WHILE loop / DO UNTIL loop / REPEAT UNTIL loop)$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;

INSERT INTO public.assessment_questions (id, track, board, topic, marks, ability, answer_format, question)
VALUES ($aq$ocr-iteration-02$aq$, 'gcse', $aq$ocr$aq$, $aq$iteration$aq$, 2, 1, $aq$text$aq$, $aq$A program asks a user to enter a password. It keeps asking until the password is correct.

Explain why a condition-controlled loop is more suitable for this program than a count-controlled loop. [2]$aq$)
ON CONFLICT (id) DO UPDATE SET board = EXCLUDED.board, topic = EXCLUDED.topic, marks = EXCLUDED.marks,
  ability = EXCLUDED.ability, answer_format = EXCLUDED.answer_format, question = EXCLUDED.question;
DELETE FROM public.assessment_mark_points WHERE question_id = $aq$ocr-iteration-02$aq$ AND position > 3;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$ocr-iteration-02$aq$, 1, $aq$The number of attempts the user will need is not known in advance / could be any number$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$ocr-iteration-02$aq$, 2, $aq$A condition-controlled loop repeats until a condition is met / until the password is correct$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$ocr-iteration-02$aq$, 3, $aq$A count-controlled loop repeats a fixed / set number of times$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;

INSERT INTO public.assessment_questions (id, track, board, topic, marks, ability, answer_format, question)
VALUES ($aq$ocr-iteration-03$aq$, 'gcse', $aq$ocr$aq$, $aq$iteration$aq$, 3, 2, $aq$text$aq$, $aq$The following program is written in OCR Exam Reference Language.

```
total = 0
for i = 1 to 4
    total = total + i
next i
print(total)
```

(a) State the value that is output when the program is run. [1]

(b) State the number of times the line `total = total + i` is executed. [1]

(c) State the purpose of the variable `total`. [1]$aq$)
ON CONFLICT (id) DO UPDATE SET board = EXCLUDED.board, topic = EXCLUDED.topic, marks = EXCLUDED.marks,
  ability = EXCLUDED.ability, answer_format = EXCLUDED.answer_format, question = EXCLUDED.question;
DELETE FROM public.assessment_mark_points WHERE question_id = $aq$ocr-iteration-03$aq$ AND position > 3;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$ocr-iteration-03$aq$, 1, $aq$(a) 10$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$ocr-iteration-03$aq$, 2, $aq$(b) 4 (times)$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$ocr-iteration-03$aq$, 3, $aq$(c) It stores / holds the running total (sum) of the values of i$aq$, 1, $aq$Accept: it adds up the numbers.$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;

INSERT INTO public.assessment_questions (id, track, board, topic, marks, ability, answer_format, question)
VALUES ($aq$ocr-iteration-04$aq$, 'gcse', $aq$ocr$aq$, $aq$iteration$aq$, 4, 2, $aq$code$aq$, $aq$Write a program that asks the user to enter a number between 1 and 10. The program must keep asking until a valid number is entered. When a valid number is entered, the program outputs "Thank you". [4]

You may use pseudocode or a high-level programming language.$aq$)
ON CONFLICT (id) DO UPDATE SET board = EXCLUDED.board, topic = EXCLUDED.topic, marks = EXCLUDED.marks,
  ability = EXCLUDED.ability, answer_format = EXCLUDED.answer_format, question = EXCLUDED.question;
DELETE FROM public.assessment_mark_points WHERE question_id = $aq$ocr-iteration-04$aq$ AND position > 4;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$ocr-iteration-04$aq$, 1, $aq$Takes a number as input from the user and stores it in a variable$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$ocr-iteration-04$aq$, 2, $aq$Uses a condition-controlled loop (WHILE / DO UNTIL / REPEAT UNTIL)$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$ocr-iteration-04$aq$, 3, $aq$Loop condition is correct: repeats while the number is less than 1 OR greater than 10$aq$, 1, $aq$Accept the equivalent condition for a loop that stops when the number is between 1 and 10 (inclusive).$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$ocr-iteration-04$aq$, 4, $aq$Asks for the number again inside the loop AND outputs "Thank you" after the loop (once, when valid)$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;

INSERT INTO public.assessment_questions (id, track, board, topic, marks, ability, answer_format, question)
VALUES ($aq$ocr-iteration-05$aq$, 'gcse', $aq$ocr$aq$, $aq$iteration$aq$, 6, 3, $aq$code$aq$, $aq$A teacher wants a program to help with marking. The program must:

- ask the user to enter five test marks, one at a time
- calculate and output the average (mean) mark
- output the highest mark entered. [6]

Write the program. You may use pseudocode or a high-level programming language.$aq$)
ON CONFLICT (id) DO UPDATE SET board = EXCLUDED.board, topic = EXCLUDED.topic, marks = EXCLUDED.marks,
  ability = EXCLUDED.ability, answer_format = EXCLUDED.answer_format, question = EXCLUDED.question;
DELETE FROM public.assessment_mark_points WHERE question_id = $aq$ocr-iteration-05$aq$ AND position > 6;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$ocr-iteration-05$aq$, 1, $aq$Uses a count-controlled loop that repeats five times$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$ocr-iteration-05$aq$, 2, $aq$Takes each mark as an input inside the loop$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$ocr-iteration-05$aq$, 3, $aq$Adds each mark to a running total (total initialised to 0 before the loop)$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$ocr-iteration-05$aq$, 4, $aq$Compares each mark with the highest so far and updates the highest when a larger mark is found$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$ocr-iteration-05$aq$, 5, $aq$Calculates the average after the loop (total divided by 5)$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$ocr-iteration-05$aq$, 6, $aq$Outputs both the average and the highest mark (after the loop)$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;

INSERT INTO public.assessment_questions (id, track, board, topic, marks, ability, answer_format, question)
VALUES ($aq$ocr-selection-01$aq$, 'gcse', $aq$ocr$aq$, $aq$selection$aq$, 1, 1, $aq$text$aq$, $aq$State what is meant by selection in a program. [1]$aq$)
ON CONFLICT (id) DO UPDATE SET board = EXCLUDED.board, topic = EXCLUDED.topic, marks = EXCLUDED.marks,
  ability = EXCLUDED.ability, answer_format = EXCLUDED.answer_format, question = EXCLUDED.question;
DELETE FROM public.assessment_mark_points WHERE question_id = $aq$ocr-selection-01$aq$ AND position > 1;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$ocr-selection-01$aq$, 1, $aq$A decision is made in the program / different code runs depending on whether a condition is true or false$aq$, 1, $aq$Accept: an example using IF.$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;

INSERT INTO public.assessment_questions (id, track, board, topic, marks, ability, answer_format, question)
VALUES ($aq$ocr-selection-02$aq$, 'gcse', $aq$ocr$aq$, $aq$selection$aq$, 2, 1, $aq$text$aq$, $aq$In the OCR Exam Reference Language, the symbols `=` and `==` are used in programs.

State the purpose of each symbol. [2]$aq$)
ON CONFLICT (id) DO UPDATE SET board = EXCLUDED.board, topic = EXCLUDED.topic, marks = EXCLUDED.marks,
  ability = EXCLUDED.ability, answer_format = EXCLUDED.answer_format, question = EXCLUDED.question;
DELETE FROM public.assessment_mark_points WHERE question_id = $aq$ocr-selection-02$aq$ AND position > 2;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$ocr-selection-02$aq$, 1, $aq$`=` assigns a value to a variable (assignment)$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$ocr-selection-02$aq$, 2, $aq$`==` compares two values to check whether they are equal (comparison)$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;

INSERT INTO public.assessment_questions (id, track, board, topic, marks, ability, answer_format, question)
VALUES ($aq$ocr-selection-03$aq$, 'gcse', $aq$ocr$aq$, $aq$selection$aq$, 3, 2, $aq$text$aq$, $aq$The following program is written in OCR Exam Reference Language.

```
mark = int(input("Enter mark"))
if mark >= 70 then
    print("Distinction")
elseif mark >= 50 then
    print("Pass")
else
    print("Fail")
endif
```

State the output when the user enters:

(a) 72 [1]

(b) 50 [1]

(c) 49 [1]$aq$)
ON CONFLICT (id) DO UPDATE SET board = EXCLUDED.board, topic = EXCLUDED.topic, marks = EXCLUDED.marks,
  ability = EXCLUDED.ability, answer_format = EXCLUDED.answer_format, question = EXCLUDED.question;
DELETE FROM public.assessment_mark_points WHERE question_id = $aq$ocr-selection-03$aq$ AND position > 3;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$ocr-selection-03$aq$, 1, $aq$(a) Distinction$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$ocr-selection-03$aq$, 2, $aq$(b) Pass$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$ocr-selection-03$aq$, 3, $aq$(c) Fail$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;

INSERT INTO public.assessment_questions (id, track, board, topic, marks, ability, answer_format, question)
VALUES ($aq$ocr-selection-04$aq$, 'gcse', $aq$ocr$aq$, $aq$selection$aq$, 4, 2, $aq$code$aq$, $aq$A cinema sells tickets.

- Children (under 16) pay £10.
- Adults pay £15.
- Adults who show a student card pay £12.

Write a program that asks the user for their age and, if they are 16 or over, asks whether they have a student card ("yes" or "no"). The program then outputs the ticket price. [4]

You may use pseudocode or a high-level programming language.$aq$)
ON CONFLICT (id) DO UPDATE SET board = EXCLUDED.board, topic = EXCLUDED.topic, marks = EXCLUDED.marks,
  ability = EXCLUDED.ability, answer_format = EXCLUDED.answer_format, question = EXCLUDED.question;
DELETE FROM public.assessment_mark_points WHERE question_id = $aq$ocr-selection-04$aq$ AND position > 4;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$ocr-selection-04$aq$, 1, $aq$Takes the age (and the student card answer) as input and stores them in variables$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$ocr-selection-04$aq$, 2, $aq$Uses selection to test the age; outputs / sets a price of £10 for under 16$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$ocr-selection-04$aq$, 3, $aq$Adult with a student card costs £12 (student card answer compared correctly)$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$ocr-selection-04$aq$, 4, $aq$Adult without a student card costs £15 AND the price is output in every case$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;

INSERT INTO public.assessment_questions (id, track, board, topic, marks, ability, answer_format, question)
VALUES ($aq$ocr-selection-05$aq$, 'gcse', $aq$ocr$aq$, $aq$selection$aq$, 6, 3, $aq$code$aq$, $aq$A game gives players a star rating from their score. The score must be a whole number from 0 to 100.

| Score | Output |
|---|---|
| 90 to 100 | 3 stars |
| 60 to 89 | 2 stars |
| 30 to 59 | 1 star |
| 0 to 29 | No stars |

Write a program that asks the user to enter a score. If the score is outside the range 0 to 100 the program outputs "Invalid". Otherwise it outputs the correct rating. [6]

You may use pseudocode or a high-level programming language.$aq$)
ON CONFLICT (id) DO UPDATE SET board = EXCLUDED.board, topic = EXCLUDED.topic, marks = EXCLUDED.marks,
  ability = EXCLUDED.ability, answer_format = EXCLUDED.answer_format, question = EXCLUDED.question;
DELETE FROM public.assessment_mark_points WHERE question_id = $aq$ocr-selection-05$aq$ AND position > 6;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$ocr-selection-05$aq$, 1, $aq$Takes the score as input and stores it in a variable$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$ocr-selection-05$aq$, 2, $aq$Tests whether the score is invalid (below 0 OR above 100) and outputs "Invalid"$aq$, 1, $aq$Both limits must be checked. Accept a range check written the other way round.$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$ocr-selection-05$aq$, 3, $aq$Ratings are only output when the score is valid (correct use of ELSE / nested selection)$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$ocr-selection-05$aq$, 4, $aq$Outputs "3 stars" for 90 to 100 (boundary correct)$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$ocr-selection-05$aq$, 5, $aq$Outputs "2 stars" for 60 to 89 (boundaries correct)$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$ocr-selection-05$aq$, 6, $aq$Outputs "1 star" for 30 to 59 AND "No stars" for 0 to 29 (boundaries correct)$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;

INSERT INTO public.assessment_questions (id, track, board, topic, marks, ability, answer_format, question)
VALUES ($aq$ocr-functions-01$aq$, 'gcse', $aq$ocr$aq$, $aq$functions$aq$, 2, 1, $aq$text$aq$, $aq$State **two** benefits of using subprograms in a program. [2]$aq$)
ON CONFLICT (id) DO UPDATE SET board = EXCLUDED.board, topic = EXCLUDED.topic, marks = EXCLUDED.marks,
  ability = EXCLUDED.ability, answer_format = EXCLUDED.answer_format, question = EXCLUDED.question;
DELETE FROM public.assessment_mark_points WHERE question_id = $aq$ocr-functions-01$aq$ AND position > 5;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$ocr-functions-01$aq$, 1, $aq$Code can be reused / written once and called many times$aq$, 1, $aq$Do not accept "easier" without a reason.$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$ocr-functions-01$aq$, 2, $aq$Reduces repetition / makes the program shorter$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$ocr-functions-01$aq$, 3, $aq$Easier to test / debug (each subprogram can be tested separately)$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$ocr-functions-01$aq$, 4, $aq$Makes the program easier to read / maintain / understand$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$ocr-functions-01$aq$, 5, $aq$Different programmers can work on different subprograms at the same time$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;

INSERT INTO public.assessment_questions (id, track, board, topic, marks, ability, answer_format, question)
VALUES ($aq$ocr-functions-02$aq$, 'gcse', $aq$ocr$aq$, $aq$functions$aq$, 2, 1, $aq$text$aq$, $aq$State the difference between a function and a procedure. [2]$aq$)
ON CONFLICT (id) DO UPDATE SET board = EXCLUDED.board, topic = EXCLUDED.topic, marks = EXCLUDED.marks,
  ability = EXCLUDED.ability, answer_format = EXCLUDED.answer_format, question = EXCLUDED.question;
DELETE FROM public.assessment_mark_points WHERE question_id = $aq$ocr-functions-02$aq$ AND position > 2;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$ocr-functions-02$aq$, 1, $aq$A function returns a value (to the part of the program that called it)$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$ocr-functions-02$aq$, 2, $aq$A procedure does not return a value$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;

INSERT INTO public.assessment_questions (id, track, board, topic, marks, ability, answer_format, question)
VALUES ($aq$ocr-functions-03$aq$, 'gcse', $aq$ocr$aq$, $aq$functions$aq$, 3, 2, $aq$text$aq$, $aq$The following program is written in OCR Exam Reference Language.

```
function double(n)
    return n * 2
endfunction

result = double(7)
print(result)
```

(a) Identify the parameter of the function. [1]

(b) State the value that is output. [1]

(c) Identify the line of code that calls the function. [1]$aq$)
ON CONFLICT (id) DO UPDATE SET board = EXCLUDED.board, topic = EXCLUDED.topic, marks = EXCLUDED.marks,
  ability = EXCLUDED.ability, answer_format = EXCLUDED.answer_format, question = EXCLUDED.question;
DELETE FROM public.assessment_mark_points WHERE question_id = $aq$ocr-functions-03$aq$ AND position > 3;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$ocr-functions-03$aq$, 1, $aq$(a) n$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$ocr-functions-03$aq$, 2, $aq$(b) 14$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$ocr-functions-03$aq$, 3, $aq$(c) result = double(7)$aq$, 1, $aq$Accept the function call double(7).$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;

INSERT INTO public.assessment_questions (id, track, board, topic, marks, ability, answer_format, question)
VALUES ($aq$ocr-functions-04$aq$, 'gcse', $aq$ocr$aq$, $aq$functions$aq$, 4, 2, $aq$code$aq$, $aq$Write a function called `areaRect` that takes the width and the length of a rectangle as parameters and returns its area.

Then write a line of code that calls the function with the values 4 and 6 and outputs the result. [4]

You may use pseudocode or a high-level programming language.$aq$)
ON CONFLICT (id) DO UPDATE SET board = EXCLUDED.board, topic = EXCLUDED.topic, marks = EXCLUDED.marks,
  ability = EXCLUDED.ability, answer_format = EXCLUDED.answer_format, question = EXCLUDED.question;
DELETE FROM public.assessment_mark_points WHERE question_id = $aq$ocr-functions-04$aq$ AND position > 4;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$ocr-functions-04$aq$, 1, $aq$Function is defined with the name areaRect and two parameters$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$ocr-functions-04$aq$, 2, $aq$Calculates the area by multiplying width by length$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$ocr-functions-04$aq$, 3, $aq$Returns the area from the function (uses return)$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$ocr-functions-04$aq$, 4, $aq$Calls the function with the arguments 4 and 6 AND outputs the returned value$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;

INSERT INTO public.assessment_questions (id, track, board, topic, marks, ability, answer_format, question)
VALUES ($aq$ocr-functions-05$aq$, 'gcse', $aq$ocr$aq$, $aq$functions$aq$, 6, 3, $aq$code$aq$, $aq$A website only accepts a password that is at least 8 characters long and contains at least one digit (0 to 9).

(a) Write a function called `isValid` that takes a password as a parameter. It returns `True` if the password meets both rules and `False` if it does not. [4]

(b) Write the program that keeps asking the user to enter a password until `isValid` returns `True`, then outputs "Password accepted". [2]

You may use pseudocode or a high-level programming language.$aq$)
ON CONFLICT (id) DO UPDATE SET board = EXCLUDED.board, topic = EXCLUDED.topic, marks = EXCLUDED.marks,
  ability = EXCLUDED.ability, answer_format = EXCLUDED.answer_format, question = EXCLUDED.question;
DELETE FROM public.assessment_mark_points WHERE question_id = $aq$ocr-functions-05$aq$ AND position > 6;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$ocr-functions-05$aq$, 1, $aq$(a) Function defined with one parameter$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$ocr-functions-05$aq$, 2, $aq$(a) Checks that the length of the password is at least 8$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$ocr-functions-05$aq$, 3, $aq$(a) Loops through the characters AND checks whether a character is a digit$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$ocr-functions-05$aq$, 4, $aq$(a) Returns True only when both rules are met, otherwise False$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$ocr-functions-05$aq$, 5, $aq$(b) Uses a loop that asks for the password again until isValid returns True$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$ocr-functions-05$aq$, 6, $aq$(b) Calls isValid with the entered password AND outputs "Password accepted" after the loop$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;

INSERT INTO public.assessment_questions (id, track, board, topic, marks, ability, answer_format, question)
VALUES ($aq$aqa-iteration-01$aq$, 'gcse', $aq$aqa$aq$, $aq$iteration$aq$, 1, 1, $aq$text$aq$, $aq$State what is meant by iteration. [1]$aq$)
ON CONFLICT (id) DO UPDATE SET board = EXCLUDED.board, topic = EXCLUDED.topic, marks = EXCLUDED.marks,
  ability = EXCLUDED.ability, answer_format = EXCLUDED.answer_format, question = EXCLUDED.question;
DELETE FROM public.assessment_mark_points WHERE question_id = $aq$aqa-iteration-01$aq$ AND position > 1;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$aqa-iteration-01$aq$, 1, $aq$Repeating a set of instructions / a section of code (a number of times or until a condition is met)$aq$, 1, $aq$Allow: looping.$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;

INSERT INTO public.assessment_questions (id, track, board, topic, marks, ability, answer_format, question)
VALUES ($aq$aqa-iteration-02$aq$, 'gcse', $aq$aqa$aq$, $aq$iteration$aq$, 2, 1, $aq$text$aq$, $aq$Describe the difference between count-controlled iteration and condition-controlled iteration. [2]$aq$)
ON CONFLICT (id) DO UPDATE SET board = EXCLUDED.board, topic = EXCLUDED.topic, marks = EXCLUDED.marks,
  ability = EXCLUDED.ability, answer_format = EXCLUDED.answer_format, question = EXCLUDED.question;
DELETE FROM public.assessment_mark_points WHERE question_id = $aq$aqa-iteration-02$aq$ AND position > 2;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$aqa-iteration-02$aq$, 1, $aq$Count-controlled iteration repeats a fixed / set number of times (the number of repeats is known)$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$aqa-iteration-02$aq$, 2, $aq$Condition-controlled iteration repeats until / while a condition is met (the number of repeats may not be known)$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;

INSERT INTO public.assessment_questions (id, track, board, topic, marks, ability, answer_format, question)
VALUES ($aq$aqa-iteration-03$aq$, 'gcse', $aq$aqa$aq$, $aq$iteration$aq$, 3, 2, $aq$text$aq$, $aq$The following algorithm is written in pseudo-code.

```
total ← 0
FOR i ← 1 TO 5
  total ← total + i * 2
ENDFOR
OUTPUT total
```

(a) State the value that is output by the algorithm. [1]

(b) State the number of times the statement `total ← total + i * 2` is executed. [1]

(c) Name the type of iteration used in the algorithm. [1]$aq$)
ON CONFLICT (id) DO UPDATE SET board = EXCLUDED.board, topic = EXCLUDED.topic, marks = EXCLUDED.marks,
  ability = EXCLUDED.ability, answer_format = EXCLUDED.answer_format, question = EXCLUDED.question;
DELETE FROM public.assessment_mark_points WHERE question_id = $aq$aqa-iteration-03$aq$ AND position > 3;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$aqa-iteration-03$aq$, 1, $aq$(a) 30$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$aqa-iteration-03$aq$, 2, $aq$(b) 5 (times)$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$aqa-iteration-03$aq$, 3, $aq$(c) Count-controlled (iteration)$aq$, 1, $aq$Allow: definite iteration.$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;

INSERT INTO public.assessment_questions (id, track, board, topic, marks, ability, answer_format, question)
VALUES ($aq$aqa-iteration-04$aq$, 'gcse', $aq$aqa$aq$, $aq$iteration$aq$, 4, 2, $aq$code$aq$, $aq$Write an algorithm that asks the user to enter a positive number. The algorithm must keep asking until a positive number is entered. It then outputs the square of the number (the number multiplied by itself). [4]

You may use pseudo-code or a high-level programming language.$aq$)
ON CONFLICT (id) DO UPDATE SET board = EXCLUDED.board, topic = EXCLUDED.topic, marks = EXCLUDED.marks,
  ability = EXCLUDED.ability, answer_format = EXCLUDED.answer_format, question = EXCLUDED.question;
DELETE FROM public.assessment_mark_points WHERE question_id = $aq$aqa-iteration-04$aq$ AND position > 4;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$aqa-iteration-04$aq$, 1, $aq$Takes a number as input from the user and stores it$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$aqa-iteration-04$aq$, 2, $aq$Uses condition-controlled iteration (WHILE / REPEAT UNTIL)$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$aqa-iteration-04$aq$, 3, $aq$Condition is correct: repeats while the number is not greater than 0$aq$, 1, $aq$Allow the equivalent condition for a loop that stops when the number is greater than 0.$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$aqa-iteration-04$aq$, 4, $aq$Outputs the number multiplied by itself after the iteration (once)$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;

INSERT INTO public.assessment_questions (id, track, board, topic, marks, ability, answer_format, question)
VALUES ($aq$aqa-iteration-05$aq$, 'gcse', $aq$aqa$aq$, $aq$iteration$aq$, 6, 3, $aq$code$aq$, $aq$A shop till program is being written. The user enters the price of each item, one at a time. The user enters -1 when there are no more items.

Write an algorithm that:

- repeatedly asks the user to enter a price until -1 is entered
- calculates the total cost of all the items
- counts the number of items entered
- outputs the total cost and the number of items. [6]

The value -1 must not be included in the total or the count. You may use pseudo-code or a high-level programming language.$aq$)
ON CONFLICT (id) DO UPDATE SET board = EXCLUDED.board, topic = EXCLUDED.topic, marks = EXCLUDED.marks,
  ability = EXCLUDED.ability, answer_format = EXCLUDED.answer_format, question = EXCLUDED.question;
DELETE FROM public.assessment_mark_points WHERE question_id = $aq$aqa-iteration-05$aq$ AND position > 6;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$aqa-iteration-05$aq$, 1, $aq$Total and count are initialised to 0 before the iteration$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$aqa-iteration-05$aq$, 2, $aq$Uses iteration that repeatedly takes a price as input$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$aqa-iteration-05$aq$, 3, $aq$Iteration stops when -1 is entered (condition correct)$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$aqa-iteration-05$aq$, 4, $aq$The value -1 is not added to the total and not counted (e.g. test before adding)$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$aqa-iteration-05$aq$, 5, $aq$Adds each price to the total AND adds 1 to the count for each item$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$aqa-iteration-05$aq$, 6, $aq$Outputs the total AND the count after the iteration$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;

INSERT INTO public.assessment_questions (id, track, board, topic, marks, ability, answer_format, question)
VALUES ($aq$aqa-selection-01$aq$, 'gcse', $aq$aqa$aq$, $aq$selection$aq$, 1, 1, $aq$text$aq$, $aq$Give **one** example of a relational (comparison) operator. [1]$aq$)
ON CONFLICT (id) DO UPDATE SET board = EXCLUDED.board, topic = EXCLUDED.topic, marks = EXCLUDED.marks,
  ability = EXCLUDED.ability, answer_format = EXCLUDED.answer_format, question = EXCLUDED.question;
DELETE FROM public.assessment_mark_points WHERE question_id = $aq$aqa-selection-01$aq$ AND position > 1;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$aqa-selection-01$aq$, 1, $aq$Any one of: =, ≠ (allow: !=, <>), <, >, ≤ (allow: <=), ≥ (allow: >=)$aq$, 1, $aq$Do not allow AND / OR / NOT (these are Boolean operators).$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;

INSERT INTO public.assessment_questions (id, track, board, topic, marks, ability, answer_format, question)
VALUES ($aq$aqa-selection-02$aq$, 'gcse', $aq$aqa$aq$, $aq$selection$aq$, 2, 1, $aq$text$aq$, $aq$Explain why an ELSE clause is used in an IF statement. [2]$aq$)
ON CONFLICT (id) DO UPDATE SET board = EXCLUDED.board, topic = EXCLUDED.topic, marks = EXCLUDED.marks,
  ability = EXCLUDED.ability, answer_format = EXCLUDED.answer_format, question = EXCLUDED.question;
DELETE FROM public.assessment_mark_points WHERE question_id = $aq$aqa-selection-02$aq$ AND position > 2;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$aqa-selection-02$aq$, 1, $aq$To run (an alternative set of) code / instructions$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$aqa-selection-02$aq$, 2, $aq$When the condition is false / when none of the conditions are met$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;

INSERT INTO public.assessment_questions (id, track, board, topic, marks, ability, answer_format, question)
VALUES ($aq$aqa-selection-03$aq$, 'gcse', $aq$aqa$aq$, $aq$selection$aq$, 3, 2, $aq$text$aq$, $aq$The following algorithm is written in pseudo-code.

```
temp ← USERINPUT
IF temp > 30 THEN
  OUTPUT 'Hot'
ELSE IF temp >= 15 THEN
  OUTPUT 'Warm'
ELSE
  OUTPUT 'Cold'
ENDIF
```

State the output when the user enters:

(a) 30 [1]

(b) 31 [1]

(c) 14 [1]$aq$)
ON CONFLICT (id) DO UPDATE SET board = EXCLUDED.board, topic = EXCLUDED.topic, marks = EXCLUDED.marks,
  ability = EXCLUDED.ability, answer_format = EXCLUDED.answer_format, question = EXCLUDED.question;
DELETE FROM public.assessment_mark_points WHERE question_id = $aq$aqa-selection-03$aq$ AND position > 3;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$aqa-selection-03$aq$, 1, $aq$(a) Warm$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$aqa-selection-03$aq$, 2, $aq$(b) Hot$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$aqa-selection-03$aq$, 3, $aq$(c) Cold$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;

INSERT INTO public.assessment_questions (id, track, board, topic, marks, ability, answer_format, question)
VALUES ($aq$aqa-selection-04$aq$, 'gcse', $aq$aqa$aq$, $aq$selection$aq$, 4, 2, $aq$code$aq$, $aq$A quiz program asks the question "What is 7 × 8?".

Write an algorithm that takes the user's answer as input. The algorithm outputs "Correct" if the answer is 56, "Too high" if the answer is greater than 56 and "Too low" otherwise. [4]

You may use pseudo-code or a high-level programming language.$aq$)
ON CONFLICT (id) DO UPDATE SET board = EXCLUDED.board, topic = EXCLUDED.topic, marks = EXCLUDED.marks,
  ability = EXCLUDED.ability, answer_format = EXCLUDED.answer_format, question = EXCLUDED.question;
DELETE FROM public.assessment_mark_points WHERE question_id = $aq$aqa-selection-04$aq$ AND position > 4;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$aqa-selection-04$aq$, 1, $aq$Takes the answer as input and stores it in a variable$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$aqa-selection-04$aq$, 2, $aq$Outputs "Correct" when the answer is 56$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$aqa-selection-04$aq$, 3, $aq$Outputs "Too high" when the answer is greater than 56$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$aqa-selection-04$aq$, 4, $aq$Outputs "Too low" otherwise AND uses a valid selection structure (each message output only in its own case)$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;

INSERT INTO public.assessment_questions (id, track, board, topic, marks, ability, answer_format, question)
VALUES ($aq$aqa-selection-05$aq$, 'gcse', $aq$aqa$aq$, $aq$selection$aq$, 6, 3, $aq$code$aq$, $aq$A leisure centre charges for entry as shown.

| Age | Peak time | Off-peak |
|---|---|---|
| Under 5 | Free | Free |
| 5 to 17 | £4 | £3 |
| 18 or over | £8 | £6 |

Write an algorithm that asks the user for their age and whether they are visiting at peak time ("Y" or "N"). The algorithm outputs the price. [6]

You may use pseudo-code or a high-level programming language.$aq$)
ON CONFLICT (id) DO UPDATE SET board = EXCLUDED.board, topic = EXCLUDED.topic, marks = EXCLUDED.marks,
  ability = EXCLUDED.ability, answer_format = EXCLUDED.answer_format, question = EXCLUDED.question;
DELETE FROM public.assessment_mark_points WHERE question_id = $aq$aqa-selection-05$aq$ AND position > 6;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$aqa-selection-05$aq$, 1, $aq$Takes the age AND the peak time answer as input$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$aqa-selection-05$aq$, 2, $aq$Outputs / sets a price of 0 for an age under 5$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$aqa-selection-05$aq$, 3, $aq$Condition for the 5 to 17 age group is correct (both limits)$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$aqa-selection-05$aq$, 4, $aq$Prices for 5 to 17 are correct for both peak (£4) and off-peak (£3)$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$aqa-selection-05$aq$, 5, $aq$Prices for 18 or over are correct for both peak (£8) and off-peak (£6)$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$aqa-selection-05$aq$, 6, $aq$The price is output in every case (using a variable or an output in each branch)$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;

INSERT INTO public.assessment_questions (id, track, board, topic, marks, ability, answer_format, question)
VALUES ($aq$aqa-functions-01$aq$, 'gcse', $aq$aqa$aq$, $aq$functions$aq$, 2, 1, $aq$text$aq$, $aq$Describe what is meant by a parameter of a subroutine. [2]$aq$)
ON CONFLICT (id) DO UPDATE SET board = EXCLUDED.board, topic = EXCLUDED.topic, marks = EXCLUDED.marks,
  ability = EXCLUDED.ability, answer_format = EXCLUDED.answer_format, question = EXCLUDED.question;
DELETE FROM public.assessment_mark_points WHERE question_id = $aq$aqa-functions-01$aq$ AND position > 2;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$aqa-functions-01$aq$, 1, $aq$A value (variable) that is passed into a subroutine / a piece of data given to the subroutine when it is called$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$aqa-functions-01$aq$, 2, $aq$It is named in the subroutine definition and is used within the subroutine (behaves like a local variable)$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;

INSERT INTO public.assessment_questions (id, track, board, topic, marks, ability, answer_format, question)
VALUES ($aq$aqa-functions-02$aq$, 'gcse', $aq$aqa$aq$, $aq$functions$aq$, 2, 1, $aq$text$aq$, $aq$State **one** difference between a local variable and a global variable. [2]$aq$)
ON CONFLICT (id) DO UPDATE SET board = EXCLUDED.board, topic = EXCLUDED.topic, marks = EXCLUDED.marks,
  ability = EXCLUDED.ability, answer_format = EXCLUDED.answer_format, question = EXCLUDED.question;
DELETE FROM public.assessment_mark_points WHERE question_id = $aq$aqa-functions-02$aq$ AND position > 2;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$aqa-functions-02$aq$, 1, $aq$A local variable can only be used / accessed within the subroutine where it is declared$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$aqa-functions-02$aq$, 2, $aq$A global variable can be used / accessed throughout the whole program (in any subroutine)$aq$, 1, $aq$Award both marks for a clear statement of the difference.$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;

INSERT INTO public.assessment_questions (id, track, board, topic, marks, ability, answer_format, question)
VALUES ($aq$aqa-functions-03$aq$, 'gcse', $aq$aqa$aq$, $aq$functions$aq$, 3, 2, $aq$text$aq$, $aq$The following algorithm is written in pseudo-code.

```
SUBROUTINE triple(n)
  RETURN n * 3
ENDSUBROUTINE

a ← triple(4)
OUTPUT a + 1
```

(a) State the value that is output. [1]

(b) State the name of the parameter of the subroutine. [1]

(c) State what the RETURN statement does. [1]$aq$)
ON CONFLICT (id) DO UPDATE SET board = EXCLUDED.board, topic = EXCLUDED.topic, marks = EXCLUDED.marks,
  ability = EXCLUDED.ability, answer_format = EXCLUDED.answer_format, question = EXCLUDED.question;
DELETE FROM public.assessment_mark_points WHERE question_id = $aq$aqa-functions-03$aq$ AND position > 3;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$aqa-functions-03$aq$, 1, $aq$(a) 13$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$aqa-functions-03$aq$, 2, $aq$(b) n$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$aqa-functions-03$aq$, 3, $aq$(c) It sends a value back to the place where the subroutine was called$aq$, 1, $aq$Allow: ends the subroutine and gives back a value.$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;

INSERT INTO public.assessment_questions (id, track, board, topic, marks, ability, answer_format, question)
VALUES ($aq$aqa-functions-04$aq$, 'gcse', $aq$aqa$aq$, $aq$functions$aq$, 4, 2, $aq$code$aq$, $aq$Write a subroutine called `average` that takes three numbers as parameters and returns their mean.

Then write a line of code that calls the subroutine with the values 4, 7 and 10 and outputs the result. [4]

You may use pseudo-code or a high-level programming language.$aq$)
ON CONFLICT (id) DO UPDATE SET board = EXCLUDED.board, topic = EXCLUDED.topic, marks = EXCLUDED.marks,
  ability = EXCLUDED.ability, answer_format = EXCLUDED.answer_format, question = EXCLUDED.question;
DELETE FROM public.assessment_mark_points WHERE question_id = $aq$aqa-functions-04$aq$ AND position > 4;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$aqa-functions-04$aq$, 1, $aq$Subroutine is defined with the name average and three parameters$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$aqa-functions-04$aq$, 2, $aq$Calculates the mean by adding the three numbers and dividing by 3 (correct order of operations)$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$aqa-functions-04$aq$, 3, $aq$Returns the mean from the subroutine$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$aqa-functions-04$aq$, 4, $aq$Calls the subroutine with 4, 7 and 10 AND outputs the returned value$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;

INSERT INTO public.assessment_questions (id, track, board, topic, marks, ability, answer_format, question)
VALUES ($aq$aqa-functions-05$aq$, 'gcse', $aq$aqa$aq$, $aq$functions$aq$, 6, 3, $aq$code$aq$, $aq$Write a subroutine called `countVowels` that takes a string as a parameter and returns the number of vowels (a, e, i, o, u) in the string.

Then write the code that asks the user to enter a word, calls `countVowels` and outputs the number of vowels. [6]

You may use pseudo-code or a high-level programming language.$aq$)
ON CONFLICT (id) DO UPDATE SET board = EXCLUDED.board, topic = EXCLUDED.topic, marks = EXCLUDED.marks,
  ability = EXCLUDED.ability, answer_format = EXCLUDED.answer_format, question = EXCLUDED.question;
DELETE FROM public.assessment_mark_points WHERE question_id = $aq$aqa-functions-05$aq$ AND position > 6;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$aqa-functions-05$aq$, 1, $aq$Subroutine defined with the name countVowels and one parameter$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$aqa-functions-05$aq$, 2, $aq$Count is initialised to 0$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$aqa-functions-05$aq$, 3, $aq$Iterates through every character of the string$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$aqa-functions-05$aq$, 4, $aq$Checks whether each character is a vowel$aq$, 1, $aq$Allow a solution that checks upper case and lower case; do not penalise if only one case is handled.$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$aqa-functions-05$aq$, 5, $aq$Adds 1 to the count for each vowel AND returns the count$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;
INSERT INTO public.assessment_mark_points (question_id, position, text, marks, guidance)
VALUES ($aq$aqa-functions-05$aq$, 6, $aq$Takes a word as input, calls the subroutine with it AND outputs the returned value$aq$, 1, $aq$$aq$)
ON CONFLICT (question_id, position) DO UPDATE SET text = EXCLUDED.text, marks = EXCLUDED.marks, guidance = EXCLUDED.guidance;

