-- Seeds the 225 homework-only tasks (25 per GCSE topic) authored in
-- src/content/*.json's "homeworkTasks" arrays, so homework can draw from a
-- pool that is architecturally separate from Lessons/Practice/Recap/Boss
-- battles (see homework_only on public.challenges, added in
-- 20260821190000_homework_only_tasks.sql). pickChallenge() in
-- src/lib/progress.ts always filters homework_only = false; the teacher's
-- "set homework" flow filters the opposite. Every task's solution was run
-- against its exact test cases through the real Pyodide runtime before this
-- migration was written.
insert into public.challenges (slug, track, topic, title, brief, difficulty, xp, homework_only) values
('gcse-files-hw-01', 'gcse', 'files', 'Write and read your name', 'See lesson content.', 1, 10, true),
('gcse-files-hw-02', 'gcse', 'files', 'Two diary lines', 'See lesson content.', 1, 15, true),
('gcse-files-hw-03', 'gcse', 'files', 'Add a task', 'See lesson content.', 2, 20, true),
('gcse-files-hw-04', 'gcse', 'files', 'Count shopping items', 'See lesson content.', 1, 10, true),
('gcse-files-hw-05', 'gcse', 'files', 'Double a stored price', 'See lesson content.', 2, 20, true),
('gcse-files-hw-06', 'gcse', 'files', 'Largest number in a file', 'See lesson content.', 2, 20, true),
('gcse-files-hw-07', 'gcse', 'files', 'Smallest number in a file', 'See lesson content.', 2, 20, true),
('gcse-files-hw-08', 'gcse', 'files', 'Words containing a letter', 'See lesson content.', 3, 25, true),
('gcse-files-hw-09', 'gcse', 'files', 'Words with a prefix', 'See lesson content.', 3, 25, true),
('gcse-files-hw-10', 'gcse', 'files', 'Names from records', 'See lesson content.', 3, 25, true),
('gcse-files-hw-11', 'gcse', 'files', 'Search for a result', 'See lesson content.', 2, 20, true),
('gcse-files-hw-12', 'gcse', 'files', 'Total characters in a file', 'See lesson content.', 3, 25, true),
('gcse-files-hw-13', 'gcse', 'files', 'Total stock from a file', 'See lesson content.', 2, 20, true),
('gcse-files-hw-14', 'gcse', 'files', 'Copy a file', 'See lesson content.', 2, 20, true),
('gcse-files-hw-15', 'gcse', 'files', 'Count freezing readings', 'See lesson content.', 2, 20, true),
('gcse-files-hw-16', 'gcse', 'files', 'Reversed note', 'See lesson content.', 2, 20, true),
('gcse-files-hw-17', 'gcse', 'files', 'Count exam passes', 'See lesson content.', 2, 20, true),
('gcse-files-hw-18', 'gcse', 'files', 'The longest line', 'See lesson content.', 3, 25, true),
('gcse-files-hw-19', 'gcse', 'files', 'Search inside a file', 'See lesson content.', 2, 20, true),
('gcse-files-hw-20', 'gcse', 'files', 'Total cost from a file', 'See lesson content.', 2, 20, true),
('gcse-files-hw-21', 'gcse', 'files', 'Sorted numbers from a file', 'See lesson content.', 2, 20, true),
('gcse-files-hw-22', 'gcse', 'files', 'Count the class list', 'See lesson content.', 1, 10, true),
('gcse-files-hw-23', 'gcse', 'files', 'Count active accounts', 'See lesson content.', 2, 20, true),
('gcse-files-hw-24', 'gcse', 'files', 'Total tickets booked', 'See lesson content.', 2, 20, true),
('gcse-files-hw-25', 'gcse', 'files', 'Comparing two files', 'See lesson content.', 3, 25, true),
('gcse-functions-hw-01', 'gcse', 'functions', 'Cube a number', 'See lesson content.', 1, 10, true),
('gcse-functions-hw-02', 'gcse', 'functions', 'Subtract two numbers', 'See lesson content.', 1, 10, true),
('gcse-functions-hw-03', 'gcse', 'functions', 'Formal greeting', 'See lesson content.', 2, 15, true),
('gcse-functions-hw-04', 'gcse', 'functions', 'Is it odd?', 'See lesson content.', 1, 10, true),
('gcse-functions-hw-05', 'gcse', 'functions', 'The larger of two', 'See lesson content.', 2, 20, true),
('gcse-functions-hw-06', 'gcse', 'functions', 'Rectangle perimeter', 'See lesson content.', 1, 10, true),
('gcse-functions-hw-07', 'gcse', 'functions', 'Average of three', 'See lesson content.', 2, 20, true),
('gcse-functions-hw-08', 'gcse', 'functions', 'Is it a vowel?', 'See lesson content.', 2, 15, true),
('gcse-functions-hw-09', 'gcse', 'functions', 'Capitalise a word', 'See lesson content.', 2, 20, true),
('gcse-functions-hw-10', 'gcse', 'functions', 'A countdown procedure', 'See lesson content.', 2, 20, true),
('gcse-functions-hw-11', 'gcse', 'functions', 'Seconds to whole minutes', 'See lesson content.', 2, 15, true),
('gcse-functions-hw-12', 'gcse', 'functions', 'Leap year function', 'See lesson content.', 4, 30, true),
('gcse-functions-hw-13', 'gcse', 'functions', 'Calculate tax', 'See lesson content.', 2, 20, true),
('gcse-functions-hw-14', 'gcse', 'functions', 'Times table procedure', 'See lesson content.', 3, 25, true),
('gcse-functions-hw-15', 'gcse', 'functions', 'Palindrome function', 'See lesson content.', 2, 20, true),
('gcse-functions-hw-16', 'gcse', 'functions', 'Combine names', 'See lesson content.', 1, 10, true),
('gcse-functions-hw-17', 'gcse', 'functions', 'Temperature advice function', 'See lesson content.', 3, 25, true),
('gcse-functions-hw-18', 'gcse', 'functions', 'Member discount function', 'See lesson content.', 3, 30, true),
('gcse-functions-hw-19', 'gcse', 'functions', 'Sum a list with a function', 'See lesson content.', 3, 25, true),
('gcse-functions-hw-20', 'gcse', 'functions', 'Count positives with two functions', 'See lesson content.', 3, 30, true),
('gcse-functions-hw-21', 'gcse', 'functions', 'Contains a digit?', 'See lesson content.', 2, 20, true),
('gcse-functions-hw-22', 'gcse', 'functions', 'Format as currency', 'See lesson content.', 1, 10, true),
('gcse-functions-hw-23', 'gcse', 'functions', 'Receipt line procedure', 'See lesson content.', 2, 20, true),
('gcse-functions-hw-24', 'gcse', 'functions', 'Order total function', 'See lesson content.', 4, 30, true),
('gcse-functions-hw-25', 'gcse', 'functions', 'Sum of squares in a list', 'See lesson content.', 3, 30, true),
('gcse-fundamentals-hw-01', 'gcse', 'fundamentals', 'Store a price', 'See lesson content.', 1, 10, true),
('gcse-fundamentals-hw-02', 'gcse', 'fundamentals', 'Store a Boolean', 'See lesson content.', 1, 10, true),
('gcse-fundamentals-hw-03', 'gcse', 'fundamentals', 'Greet by name', 'See lesson content.', 1, 10, true),
('gcse-fundamentals-hw-04', 'gcse', 'fundamentals', 'Age in five years', 'See lesson content.', 2, 15, true),
('gcse-fundamentals-hw-05', 'gcse', 'fundamentals', 'Double a distance', 'See lesson content.', 2, 15, true),
('gcse-fundamentals-hw-06', 'gcse', 'fundamentals', 'Double a whole number', 'See lesson content.', 1, 10, true),
('gcse-fundamentals-hw-07', 'gcse', 'fundamentals', 'Multiply two whole numbers', 'See lesson content.', 2, 15, true),
('gcse-fundamentals-hw-08', 'gcse', 'fundamentals', 'Halve a length', 'See lesson content.', 2, 15, true),
('gcse-fundamentals-hw-09', 'gcse', 'fundamentals', 'Is it even?', 'See lesson content.', 2, 20, true),
('gcse-fundamentals-hw-10', 'gcse', 'fundamentals', 'A single grade', 'See lesson content.', 1, 10, true),
('gcse-fundamentals-hw-11', 'gcse', 'fundamentals', 'Add ten to an input', 'See lesson content.', 2, 15, true),
('gcse-fundamentals-hw-12', 'gcse', 'fundamentals', 'Shopping total', 'See lesson content.', 3, 25, true),
('gcse-fundamentals-hw-13', 'gcse', 'fundamentals', 'Four data types', 'See lesson content.', 1, 15, true),
('gcse-fundamentals-hw-14', 'gcse', 'fundamentals', 'Is it an adult?', 'See lesson content.', 2, 20, true),
('gcse-fundamentals-hw-15', 'gcse', 'fundamentals', 'A rating out of five', 'See lesson content.', 2, 15, true),
('gcse-fundamentals-hw-16', 'gcse', 'fundamentals', 'Name and age together', 'See lesson content.', 3, 20, true),
('gcse-fundamentals-hw-17', 'gcse', 'fundamentals', 'A weight reading', 'See lesson content.', 3, 20, true),
('gcse-fundamentals-hw-18', 'gcse', 'fundamentals', 'A score out of 100', 'See lesson content.', 2, 20, true),
('gcse-fundamentals-hw-19', 'gcse', 'fundamentals', 'A race time, three ways', 'See lesson content.', 3, 25, true),
('gcse-fundamentals-hw-20', 'gcse', 'fundamentals', 'Minutes to seconds', 'See lesson content.', 2, 15, true),
('gcse-fundamentals-hw-21', 'gcse', 'fundamentals', 'Always two decimal places', 'See lesson content.', 2, 20, true),
('gcse-fundamentals-hw-22', 'gcse', 'fundamentals', 'Store a False value', 'See lesson content.', 1, 10, true),
('gcse-fundamentals-hw-23', 'gcse', 'fundamentals', 'Pet ownership summary', 'See lesson content.', 4, 30, true),
('gcse-fundamentals-hw-24', 'gcse', 'fundamentals', 'Is the total even?', 'See lesson content.', 3, 25, true),
('gcse-fundamentals-hw-25', 'gcse', 'fundamentals', 'Text vs. cast display', 'See lesson content.', 3, 25, true),
('gcse-getting-started-hw-01', 'gcse', 'getting-started', 'Print a welcome', 'See lesson content.', 1, 10, true),
('gcse-getting-started-hw-02', 'gcse', 'getting-started', 'Two lines, again', 'See lesson content.', 1, 10, true),
('gcse-getting-started-hw-03', 'gcse', 'getting-started', 'A label and a number', 'See lesson content.', 1, 10, true),
('gcse-getting-started-hw-04', 'gcse', 'getting-started', 'Four colours', 'See lesson content.', 2, 15, true),
('gcse-getting-started-hw-05', 'gcse', 'getting-started', 'Store a place', 'See lesson content.', 1, 10, true),
('gcse-getting-started-hw-06', 'gcse', 'getting-started', 'Store a whole number', 'See lesson content.', 1, 10, true),
('gcse-getting-started-hw-07', 'gcse', 'getting-started', 'Change a variable twice', 'See lesson content.', 2, 15, true),
('gcse-getting-started-hw-08', 'gcse', 'getting-started', 'Three variables, mixed order', 'See lesson content.', 2, 15, true),
('gcse-getting-started-hw-09', 'gcse', 'getting-started', 'Favourite subject', 'See lesson content.', 1, 10, true),
('gcse-getting-started-hw-10', 'gcse', 'getting-started', 'A pet''s name', 'See lesson content.', 1, 10, true),
('gcse-getting-started-hw-11', 'gcse', 'getting-started', 'Film and song', 'See lesson content.', 2, 15, true),
('gcse-getting-started-hw-12', 'gcse', 'getting-started', 'Say it three times', 'See lesson content.', 2, 15, true),
('gcse-getting-started-hw-13', 'gcse', 'getting-started', 'Reverse three words', 'See lesson content.', 3, 25, true),
('gcse-getting-started-hw-14', 'gcse', 'getting-started', 'Join two words together', 'See lesson content.', 1, 10, true),
('gcse-getting-started-hw-15', 'gcse', 'getting-started', 'Two spaced-out words', 'See lesson content.', 1, 10, true),
('gcse-getting-started-hw-16', 'gcse', 'getting-started', 'Welcome by name', 'See lesson content.', 2, 15, true),
('gcse-getting-started-hw-17', 'gcse', 'getting-started', 'Full name announcement', 'See lesson content.', 2, 20, true),
('gcse-getting-started-hw-18', 'gcse', 'getting-started', 'Silly sentence builder', 'See lesson content.', 3, 25, true),
('gcse-getting-started-hw-19', 'gcse', 'getting-started', 'A four-line rhyme', 'See lesson content.', 2, 15, true),
('gcse-getting-started-hw-20', 'gcse', 'getting-started', 'Book and author', 'See lesson content.', 2, 15, true),
('gcse-getting-started-hw-21', 'gcse', 'getting-started', 'A date, joined together', 'See lesson content.', 3, 25, true),
('gcse-getting-started-hw-22', 'gcse', 'getting-started', 'Name and colour', 'See lesson content.', 1, 10, true),
('gcse-getting-started-hw-23', 'gcse', 'getting-started', 'Four-word sentence', 'See lesson content.', 3, 25, true),
('gcse-getting-started-hw-24', 'gcse', 'getting-started', 'A whole sentence, twice', 'See lesson content.', 2, 15, true),
('gcse-getting-started-hw-25', 'gcse', 'getting-started', 'Nickname announcement', 'See lesson content.', 3, 25, true),
('gcse-iteration-hw-01', 'gcse', 'iteration', 'Count up to N', 'See lesson content.', 1, 10, true),
('gcse-iteration-hw-02', 'gcse', 'iteration', 'Sum from 1 to N', 'See lesson content.', 1, 10, true),
('gcse-iteration-hw-03', 'gcse', 'iteration', 'Times table', 'See lesson content.', 2, 20, true),
('gcse-iteration-hw-04', 'gcse', 'iteration', 'Countdown to liftoff', 'See lesson content.', 1, 10, true),
('gcse-iteration-hw-05', 'gcse', 'iteration', 'Total of N purchases', 'See lesson content.', 2, 20, true),
('gcse-iteration-hw-06', 'gcse', 'iteration', 'Count negative numbers', 'See lesson content.', 2, 20, true),
('gcse-iteration-hw-07', 'gcse', 'iteration', 'Doubling past 100', 'See lesson content.', 3, 25, true),
('gcse-iteration-hw-08', 'gcse', 'iteration', 'Sum until zero', 'See lesson content.', 2, 20, true),
('gcse-iteration-hw-09', 'gcse', 'iteration', 'Validated percentage', 'See lesson content.', 2, 20, true),
('gcse-iteration-hw-10', 'gcse', 'iteration', 'Guess the number', 'See lesson content.', 2, 20, true),
('gcse-iteration-hw-11', 'gcse', 'iteration', 'Average of N scores', 'See lesson content.', 2, 20, true),
('gcse-iteration-hw-12', 'gcse', 'iteration', 'Largest of N', 'See lesson content.', 2, 20, true),
('gcse-iteration-hw-13', 'gcse', 'iteration', 'Smallest of N', 'See lesson content.', 2, 20, true),
('gcse-iteration-hw-14', 'gcse', 'iteration', 'Count above a threshold', 'See lesson content.', 3, 25, true),
('gcse-iteration-hw-15', 'gcse', 'iteration', 'Total distance over N days', 'See lesson content.', 2, 20, true),
('gcse-iteration-hw-16', 'gcse', 'iteration', 'Square numbers', 'See lesson content.', 2, 20, true),
('gcse-iteration-hw-17', 'gcse', 'iteration', 'Sum of even numbers', 'See lesson content.', 3, 25, true),
('gcse-iteration-hw-18', 'gcse', 'iteration', 'Count multiples of three', 'See lesson content.', 2, 20, true),
('gcse-iteration-hw-19', 'gcse', 'iteration', 'List the factors', 'See lesson content.', 3, 25, true),
('gcse-iteration-hw-20', 'gcse', 'iteration', 'Total of N items', 'See lesson content.', 2, 20, true),
('gcse-iteration-hw-21', 'gcse', 'iteration', 'Sum of odd numbers', 'See lesson content.', 2, 20, true),
('gcse-iteration-hw-22', 'gcse', 'iteration', 'Filling a jar', 'See lesson content.', 3, 25, true),
('gcse-iteration-hw-23', 'gcse', 'iteration', 'Count five-star ratings', 'See lesson content.', 2, 20, true),
('gcse-iteration-hw-24', 'gcse', 'iteration', 'How many weeks will it last?', 'See lesson content.', 3, 25, true),
('gcse-iteration-hw-25', 'gcse', 'iteration', 'Growing number pattern', 'See lesson content.', 3, 30, true),
('gcse-lists-hw-01', 'gcse', 'lists', 'How many names?', 'See lesson content.', 1, 10, true),
('gcse-lists-hw-02', 'gcse', 'lists', 'Sum of scores', 'See lesson content.', 1, 10, true),
('gcse-lists-hw-03', 'gcse', 'lists', 'Count matching values', 'See lesson content.', 2, 20, true),
('gcse-lists-hw-04', 'gcse', 'lists', 'Above the threshold', 'See lesson content.', 2, 20, true),
('gcse-lists-hw-05', 'gcse', 'lists', 'Position of the smallest', 'See lesson content.', 2, 20, true),
('gcse-lists-hw-06', 'gcse', 'lists', 'Reversed words', 'See lesson content.', 1, 10, true),
('gcse-lists-hw-07', 'gcse', 'lists', 'Count unique values', 'See lesson content.', 4, 30, true),
('gcse-lists-hw-08', 'gcse', 'lists', 'Average of a list', 'See lesson content.', 1, 10, true),
('gcse-lists-hw-09', 'gcse', 'lists', 'Is it in the list?', 'See lesson content.', 1, 10, true),
('gcse-lists-hw-10', 'gcse', 'lists', 'Every other item', 'See lesson content.', 2, 20, true),
('gcse-lists-hw-11', 'gcse', 'lists', 'Over or within budget', 'See lesson content.', 3, 25, true),
('gcse-lists-hw-12', 'gcse', 'lists', 'Count within a range', 'See lesson content.', 3, 25, true),
('gcse-lists-hw-13', 'gcse', 'lists', 'First three items', 'See lesson content.', 1, 10, true),
('gcse-lists-hw-14', 'gcse', 'lists', 'Last two items', 'See lesson content.', 1, 10, true),
('gcse-lists-hw-15', 'gcse', 'lists', 'Combine two lists', 'See lesson content.', 2, 20, true),
('gcse-lists-hw-16', 'gcse', 'lists', 'Longer than the minimum', 'See lesson content.', 2, 20, true),
('gcse-lists-hw-17', 'gcse', 'lists', 'Print the whole list', 'See lesson content.', 1, 10, true),
('gcse-lists-hw-18', 'gcse', 'lists', 'A week of temperatures', 'See lesson content.', 2, 20, true),
('gcse-lists-hw-19', 'gcse', 'lists', 'Range of a list', 'See lesson content.', 2, 20, true),
('gcse-lists-hw-20', 'gcse', 'lists', 'Out of stock', 'See lesson content.', 3, 25, true),
('gcse-lists-hw-21', 'gcse', 'lists', 'Two students, two scores each', 'See lesson content.', 3, 25, true),
('gcse-lists-hw-22', 'gcse', 'lists', 'Sorted smallest to largest', 'See lesson content.', 1, 10, true),
('gcse-lists-hw-23', 'gcse', 'lists', 'Count negative values', 'See lesson content.', 2, 20, true),
('gcse-lists-hw-24', 'gcse', 'lists', 'Find or not found', 'See lesson content.', 3, 25, true),
('gcse-lists-hw-25', 'gcse', 'lists', 'Middle of a 3x3 grid', 'See lesson content.', 3, 30, true),
('gcse-selection-hw-01', 'gcse', 'selection', 'Even or odd', 'See lesson content.', 1, 10, true),
('gcse-selection-hw-02', 'gcse', 'selection', 'Positive, negative or zero', 'See lesson content.', 2, 20, true),
('gcse-selection-hw-03', 'gcse', 'selection', 'Pass or fail', 'See lesson content.', 1, 10, true),
('gcse-selection-hw-04', 'gcse', 'selection', 'Speeding check', 'See lesson content.', 1, 10, true),
('gcse-selection-hw-05', 'gcse', 'selection', 'Member discount', 'See lesson content.', 2, 20, true),
('gcse-selection-hw-06', 'gcse', 'selection', 'Free shipping', 'See lesson content.', 2, 20, true),
('gcse-selection-hw-07', 'gcse', 'selection', 'Weather advice', 'See lesson content.', 3, 25, true),
('gcse-selection-hw-08', 'gcse', 'selection', 'In range 1 to 10', 'See lesson content.', 2, 15, true),
('gcse-selection-hw-09', 'gcse', 'selection', 'Password length check', 'See lesson content.', 2, 15, true),
('gcse-selection-hw-10', 'gcse', 'selection', 'Leap year check', 'See lesson content.', 4, 30, true),
('gcse-selection-hw-11', 'gcse', 'selection', 'Grade classification', 'See lesson content.', 3, 25, true),
('gcse-selection-hw-12', 'gcse', 'selection', 'Ticket age category', 'See lesson content.', 3, 25, true),
('gcse-selection-hw-13', 'gcse', 'selection', 'Two-factor check', 'See lesson content.', 3, 25, true),
('gcse-selection-hw-14', 'gcse', 'selection', 'Simple calculator', 'See lesson content.', 3, 30, true),
('gcse-selection-hw-15', 'gcse', 'selection', 'Store open check', 'See lesson content.', 2, 20, true),
('gcse-selection-hw-16', 'gcse', 'selection', 'Ice warning', 'See lesson content.', 1, 10, true),
('gcse-selection-hw-17', 'gcse', 'selection', 'Speed category', 'See lesson content.', 2, 20, true),
('gcse-selection-hw-18', 'gcse', 'selection', 'Discount code', 'See lesson content.', 1, 15, true),
('gcse-selection-hw-19', 'gcse', 'selection', 'Multiple of 3 and 5', 'See lesson content.', 3, 25, true),
('gcse-selection-hw-20', 'gcse', 'selection', 'Refund eligibility', 'See lesson content.', 3, 25, true),
('gcse-selection-hw-21', 'gcse', 'selection', 'Membership tier', 'See lesson content.', 3, 30, true),
('gcse-selection-hw-22', 'gcse', 'selection', 'Certificate eligibility', 'See lesson content.', 3, 25, true),
('gcse-selection-hw-23', 'gcse', 'selection', 'Age category', 'See lesson content.', 2, 20, true),
('gcse-selection-hw-24', 'gcse', 'selection', 'Positive even check', 'See lesson content.', 2, 20, true),
('gcse-selection-hw-25', 'gcse', 'selection', 'Exam entry check', 'See lesson content.', 3, 25, true),
('gcse-sequencing-hw-01', 'gcse', 'sequencing', 'Add two prices', 'See lesson content.', 1, 10, true),
('gcse-sequencing-hw-02', 'gcse', 'sequencing', 'Photocopying cost', 'See lesson content.', 1, 10, true),
('gcse-sequencing-hw-03', 'gcse', 'sequencing', 'Hours to minutes', 'See lesson content.', 1, 10, true),
('gcse-sequencing-hw-04', 'gcse', 'sequencing', 'Average of two numbers', 'See lesson content.', 1, 10, true),
('gcse-sequencing-hw-05', 'gcse', 'sequencing', 'Perimeter of a square', 'See lesson content.', 1, 10, true),
('gcse-sequencing-hw-06', 'gcse', 'sequencing', '10% off', 'See lesson content.', 2, 15, true),
('gcse-sequencing-hw-07', 'gcse', 'sequencing', 'Average speed', 'See lesson content.', 2, 15, true),
('gcse-sequencing-hw-08', 'gcse', 'sequencing', 'Weeks to days', 'See lesson content.', 1, 10, true),
('gcse-sequencing-hw-09', 'gcse', 'sequencing', 'Pounds to pence', 'See lesson content.', 2, 15, true),
('gcse-sequencing-hw-10', 'gcse', 'sequencing', 'Pizza slice cost', 'See lesson content.', 1, 10, true),
('gcse-sequencing-hw-11', 'gcse', 'sequencing', 'Sharing sweets', 'See lesson content.', 2, 20, true),
('gcse-sequencing-hw-12', 'gcse', 'sequencing', 'Temperature difference', 'See lesson content.', 1, 10, true),
('gcse-sequencing-hw-13', 'gcse', 'sequencing', 'Pages per day', 'See lesson content.', 2, 15, true),
('gcse-sequencing-hw-14', 'gcse', 'sequencing', 'Journey time remaining', 'See lesson content.', 1, 10, true),
('gcse-sequencing-hw-15', 'gcse', 'sequencing', 'Scaling a recipe', 'See lesson content.', 2, 15, true),
('gcse-sequencing-hw-16', 'gcse', 'sequencing', 'Battery remaining', 'See lesson content.', 1, 10, true),
('gcse-sequencing-hw-17', 'gcse', 'sequencing', 'Volume of a box', 'See lesson content.', 2, 20, true),
('gcse-sequencing-hw-18', 'gcse', 'sequencing', 'Age gap', 'See lesson content.', 1, 10, true),
('gcse-sequencing-hw-19', 'gcse', 'sequencing', 'Adding VAT', 'See lesson content.', 2, 15, true),
('gcse-sequencing-hw-20', 'gcse', 'sequencing', 'Score as a percentage', 'See lesson content.', 2, 20, true),
('gcse-sequencing-hw-21', 'gcse', 'sequencing', 'Miles to kilometres', 'See lesson content.', 1, 10, true),
('gcse-sequencing-hw-22', 'gcse', 'sequencing', 'Weekly exercise minutes', 'See lesson content.', 2, 15, true),
('gcse-sequencing-hw-23', 'gcse', 'sequencing', 'Weekly pay', 'See lesson content.', 3, 25, true),
('gcse-sequencing-hw-24', 'gcse', 'sequencing', 'Theme park tickets', 'See lesson content.', 2, 20, true),
('gcse-sequencing-hw-25', 'gcse', 'sequencing', 'Order total with delivery', 'See lesson content.', 3, 25, true),
('gcse-strings-hw-01', 'gcse', 'strings', 'Lower case it', 'See lesson content.', 1, 10, true),
('gcse-strings-hw-02', 'gcse', 'strings', 'Last three letters', 'See lesson content.', 1, 10, true),
('gcse-strings-hw-03', 'gcse', 'strings', 'Reverse a word', 'See lesson content.', 1, 10, true),
('gcse-strings-hw-04', 'gcse', 'strings', 'Does it start with...?', 'See lesson content.', 2, 15, true),
('gcse-strings-hw-05', 'gcse', 'strings', 'Does it end with...?', 'See lesson content.', 2, 15, true),
('gcse-strings-hw-06', 'gcse', 'strings', 'Remove a character', 'See lesson content.', 2, 15, true),
('gcse-strings-hw-07', 'gcse', 'strings', 'Count the words', 'See lesson content.', 1, 10, true),
('gcse-strings-hw-08', 'gcse', 'strings', 'Join words into a sentence', 'See lesson content.', 2, 20, true),
('gcse-strings-hw-09', 'gcse', 'strings', 'Is it a palindrome?', 'See lesson content.', 2, 20, true),
('gcse-strings-hw-10', 'gcse', 'strings', 'Title case a sentence', 'See lesson content.', 1, 10, true),
('gcse-strings-hw-11', 'gcse', 'strings', 'Count the vowels', 'See lesson content.', 2, 20, true),
('gcse-strings-hw-12', 'gcse', 'strings', 'Letters only?', 'See lesson content.', 1, 15, true),
('gcse-strings-hw-13', 'gcse', 'strings', 'Digits only?', 'See lesson content.', 1, 15, true),
('gcse-strings-hw-14', 'gcse', 'strings', 'Extract the domain', 'See lesson content.', 2, 20, true),
('gcse-strings-hw-15', 'gcse', 'strings', 'Remove all spaces', 'See lesson content.', 2, 15, true),
('gcse-strings-hw-16', 'gcse', 'strings', 'Repeat a word', 'See lesson content.', 1, 10, true),
('gcse-strings-hw-17', 'gcse', 'strings', 'Equal ignoring case', 'See lesson content.', 2, 15, true),
('gcse-strings-hw-18', 'gcse', 'strings', 'Find a substring', 'See lesson content.', 2, 20, true),
('gcse-strings-hw-19', 'gcse', 'strings', 'One character per line', 'See lesson content.', 1, 10, true),
('gcse-strings-hw-20', 'gcse', 'strings', 'Censor a word', 'See lesson content.', 3, 25, true),
('gcse-strings-hw-21', 'gcse', 'strings', 'Empty or blank?', 'See lesson content.', 2, 15, true),
('gcse-strings-hw-22', 'gcse', 'strings', 'A custom substring', 'See lesson content.', 3, 25, true),
('gcse-strings-hw-23', 'gcse', 'strings', 'Build an acronym', 'See lesson content.', 3, 25, true),
('gcse-strings-hw-24', 'gcse', 'strings', 'Count a substring', 'See lesson content.', 2, 20, true),
('gcse-strings-hw-25', 'gcse', 'strings', 'Alternating case', 'See lesson content.', 3, 30, true)
on conflict (slug) do nothing;
