-- Practice tasks: rows so attempts, XP and skill tracking have something to point at.
-- The wording, hints and test cases are authored in src/content/gcse-<topic>.json
-- ("practiceTasks") and merged in at render time. Every task's reference solution
-- was run against its exact test cases in the real Pyodide engine (0.26.4), and its
-- expected outputs were produced by an independent JavaScript implementation.
-- Idempotent.
insert into public.challenges (slug, track, topic, title, brief, difficulty, xp, practice_only) values
('gcse-searching-sorting-p-01', 'gcse', 'searching-sorting', 'Is it in the list?', 'See lesson content.', 1, 10, true),
('gcse-searching-sorting-p-02', 'gcse', 'searching-sorting', 'Find the position', 'See lesson content.', 2, 15, true),
('gcse-searching-sorting-p-03', 'gcse', 'searching-sorting', 'How many checks?', 'See lesson content.', 2, 15, true),
('gcse-searching-sorting-p-04', 'gcse', 'searching-sorting', 'Search a list of names', 'See lesson content.', 2, 15, true),
('gcse-searching-sorting-p-05', 'gcse', 'searching-sorting', 'How many times?', 'See lesson content.', 3, 20, true),
('gcse-searching-sorting-p-06', 'gcse', 'searching-sorting', 'Every position', 'See lesson content.', 3, 25, true),
('gcse-searching-sorting-p-07', 'gcse', 'searching-sorting', 'The last match', 'See lesson content.', 3, 25, true),
('gcse-searching-sorting-p-08', 'gcse', 'searching-sorting', 'Price lookup', 'See lesson content.', 4, 30, true),
('gcse-searching-sorting-p-09', 'gcse', 'searching-sorting', 'The middle item', 'See lesson content.', 2, 15, true),
('gcse-searching-sorting-p-10', 'gcse', 'searching-sorting', 'Is it in the sorted list?', 'See lesson content.', 3, 20, true),
('gcse-searching-sorting-p-11', 'gcse', 'searching-sorting', 'Binary search: where is it?', 'See lesson content.', 3, 25, true),
('gcse-searching-sorting-p-12', 'gcse', 'searching-sorting', 'Count the binary search checks', 'See lesson content.', 4, 30, true),
('gcse-searching-sorting-p-13', 'gcse', 'searching-sorting', 'Can we use a binary search?', 'See lesson content.', 2, 15, true),
('gcse-searching-sorting-p-14', 'gcse', 'searching-sorting', 'One bubble sort pass', 'See lesson content.', 2, 15, true),
('gcse-searching-sorting-p-15', 'gcse', 'searching-sorting', 'Count the swaps', 'See lesson content.', 3, 20, true),
('gcse-searching-sorting-p-16', 'gcse', 'searching-sorting', 'Bubble sort a list', 'See lesson content.', 3, 25, true),
('gcse-searching-sorting-p-17', 'gcse', 'searching-sorting', 'How many passes?', 'See lesson content.', 4, 30, true),
('gcse-searching-sorting-p-18', 'gcse', 'searching-sorting', 'Biggest first', 'See lesson content.', 3, 25, true),
('gcse-searching-sorting-p-19', 'gcse', 'searching-sorting', 'Insert into a sorted list', 'See lesson content.', 3, 20, true),
('gcse-searching-sorting-p-20', 'gcse', 'searching-sorting', 'Insertion sort a list', 'See lesson content.', 3, 25, true),
('gcse-searching-sorting-p-21', 'gcse', 'searching-sorting', 'Show the insertion sort steps', 'See lesson content.', 4, 30, true),
('gcse-searching-sorting-p-22', 'gcse', 'searching-sorting', 'Count the shifts', 'See lesson content.', 4, 30, true),
('gcse-searching-sorting-p-s1', 'gcse', 'searching-sorting', '🌟 Merge two sorted lists', 'See lesson content.', 5, 40, true),
('gcse-searching-sorting-p-s2', 'gcse', 'searching-sorting', '🌟 The first split of a merge sort', 'See lesson content.', 5, 40, true),
('gcse-searching-sorting-p-s3', 'gcse', 'searching-sorting', '🌟 Sort, then search', 'See lesson content.', 5, 40, true),
('gcse-searching-sorting-p-s4', 'gcse', 'searching-sorting', '🌟 Sort the names', 'See lesson content.', 5, 40, true),
('gcse-robust-programs-p-01', 'gcse', 'robust-programs', 'Is anything there?', 'See lesson content.', 1, 10, true),
('gcse-robust-programs-p-02', 'gcse', 'robust-programs', 'Rating from 1 to 5', 'See lesson content.', 1, 10, true),
('gcse-robust-programs-p-03', 'gcse', 'robust-programs', 'Username length', 'See lesson content.', 2, 15, true),
('gcse-robust-programs-p-04', 'gcse', 'robust-programs', 'A four-digit PIN', 'See lesson content.', 2, 15, true),
('gcse-robust-programs-p-05', 'gcse', 'robust-programs', 'Product code format', 'See lesson content.', 3, 25, true),
('gcse-robust-programs-p-06', 'gcse', 'robust-programs', 'Email format check', 'See lesson content.', 4, 30, true),
('gcse-robust-programs-p-07', 'gcse', 'robust-programs', 'Menu choice, ask again', 'See lesson content.', 3, 25, true),
('gcse-robust-programs-p-08', 'gcse', 'robust-programs', 'A whole number above zero', 'See lesson content.', 3, 25, true),
('gcse-robust-programs-p-09', 'gcse', 'robust-programs', 'Which password check failed?', 'See lesson content.', 3, 25, true),
('gcse-robust-programs-p-10', 'gcse', 'robust-programs', 'Is it a real date?', 'See lesson content.', 4, 30, true),
('gcse-robust-programs-p-11', 'gcse', 'robust-programs', 'Age entry: type, then range', 'See lesson content.', 3, 25, true),
('gcse-robust-programs-p-12', 'gcse', 'robust-programs', 'Card number check', 'See lesson content.', 4, 30, true),
('gcse-robust-programs-p-13', 'gcse', 'robust-programs', 'Do the passwords match?', 'See lesson content.', 1, 10, true),
('gcse-robust-programs-p-14', 'gcse', 'robust-programs', 'PIN with a leading zero', 'See lesson content.', 2, 15, true),
('gcse-robust-programs-p-15', 'gcse', 'robust-programs', 'Two accounts', 'See lesson content.', 3, 25, true),
('gcse-robust-programs-p-16', 'gcse', 'robust-programs', 'Password strength score', 'See lesson content.', 4, 30, true),
('gcse-robust-programs-p-17', 'gcse', 'robust-programs', 'Strong or weak?', 'See lesson content.', 3, 25, true),
('gcse-robust-programs-p-18', 'gcse', 'robust-programs', 'Is the username taken?', 'See lesson content.', 3, 25, true),
('gcse-robust-programs-p-19', 'gcse', 'robust-programs', 'Two-factor login', 'See lesson content.', 4, 30, true),
('gcse-robust-programs-p-20', 'gcse', 'robust-programs', 'Fix the syntax error: greeting', 'See lesson content.', 2, 15, true),
('gcse-robust-programs-p-21', 'gcse', 'robust-programs', 'Fix the syntax error: countdown', 'See lesson content.', 2, 15, true),
('gcse-robust-programs-p-22', 'gcse', 'robust-programs', 'Fix the logic error: the total', 'See lesson content.', 3, 25, true),
('gcse-robust-programs-p-23', 'gcse', 'robust-programs', 'Fix the logic error: age check', 'See lesson content.', 3, 25, true),
('gcse-robust-programs-p-24', 'gcse', 'robust-programs', 'Fix the logic error: three attempts', 'See lesson content.', 3, 25, true),
('gcse-robust-programs-p-25', 'gcse', 'robust-programs', 'Fix the logic error: at least 8', 'See lesson content.', 3, 25, true),
('gcse-robust-programs-p-26', 'gcse', 'robust-programs', 'Classify the test data', 'See lesson content.', 2, 15, true),
('gcse-robust-programs-p-27', 'gcse', 'robust-programs', 'Choose test data for a range', 'See lesson content.', 2, 15, true),
('gcse-robust-programs-p-28', 'gcse', 'robust-programs', 'A username-checking function', 'See lesson content.', 3, 25, true),
('gcse-robust-programs-p-s1', 'gcse', 'robust-programs', '🌟 Registration checker', 'See lesson content.', 5, 40, true),
('gcse-robust-programs-p-s2', 'gcse', 'robust-programs', '🌟 Tidy up a name', 'See lesson content.', 5, 40, true),
('gcse-robust-programs-p-s3', 'gcse', 'robust-programs', '🌟 Find the failing test', 'See lesson content.', 5, 40, true),
('gcse-robust-programs-p-s4', 'gcse', 'robust-programs', '🌟 Count the entries', 'See lesson content.', 5, 40, true)
on conflict (slug) do nothing;
